export const DESTINATIONS = [
  { name: "Kedarnath", slug: "kedarnath", info: "3,583m · Uttarakhand", note: "16 km trek to the Jyotirlinga", temp: "4°⛅", image: "/kedarnath.jpg", grad: "linear-gradient(150deg,#2d1b60,#5a3d7a 60%,#8a6a4a)", rot: -2, color: "#7c3aed", type: "pilgrimage" as const, activities: ["trekking", "pilgrimage"] as string[],
    wx: { icon: "⛅", temp: 4, feels: 1, hum: 55, wind: 22, aqi: 32, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Partly cloudy", alt: "3,583m", sunrise: "5:42 AM", sunset: "6:58 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 8, lo: 0 },{ day: "Thursday", icon: "⛅", hi: 6, lo: -2 },{ day: "Friday", icon: "🌧️", hi: 4, lo: -3 }] },
    routes: [
      { route: "Rishikesh → Rudraprayag", status: "open" as const, note: "NH-7, clear" },
      { route: "Rudraprayag → Guptkashi", status: "open" as const, note: "Narrow road" },
      { route: "Guptkashi → Sonprayag", status: "open" as const, note: "Clear" },
      { route: "Gaurikund → Kedarnath", status: "open" as const, note: "Trek, maintained" },
    ],
    packItems: ["Thermals ×2", "Trekking shoes", "Rain poncho", "Fleece jacket", "Power bank", "First aid kit", "Cash ₹10K+", "Char Dham e-pass"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Rudraprayag Police", number: "01364-233512" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "16 km" }, { icon: "⏱️", label: "Duration", value: "4–6 days" }, { icon: "💰", label: "Budget", value: "₹5K–35K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Spiti Valley", slug: "spiti", info: "3,650m · Himachal", note: "cold desert, ancient monasteries", temp: "10°☀️", image: "/spiti.jpg", grad: "linear-gradient(150deg,#3a3020,#5a5030 60%,#3a5040)", rot: 1.5, color: "#b45309", type: "adventure" as const, activities: ["road-trip", "biking", "camping"] as string[],
    wx: { icon: "☀️", temp: 10, feels: 7, hum: 25, wind: 8, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Clear sky", alt: "3,650m", sunrise: "5:38 AM", sunset: "7:12 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 18, lo: 2 },{ day: "Thursday", icon: "☀️", hi: 17, lo: 1 },{ day: "Friday", icon: "⛅", hi: 14, lo: 0 }] },
    routes: [
      { route: "Manali → Rohtang", status: "open" as const, note: "Clear" },
      { route: "Rohtang → Batal", status: "partial" as const, note: "BRO repair" },
      { route: "Batal → Kunzum → Kaza", status: "open" as const, note: "Gravel descent" },
      { route: "Sumdo → Reckong Peo", status: "partial" as const, note: "Rockfall zone" },
    ],
    packItems: ["Down jacket", "Thermals ×2", "Jerry can (fuel)", "Cash ₹15K+", "Power bank ×2", "Sleeping bag", "Sunglasses UV400", "ILP + Rohtang permit"],
    emergency: [{ name: "Kaza PHC", number: "01906-222340" }, { name: "BRO Helpline", number: "1800-180-6763" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛣️", label: "Circuit", value: "~630 km" }, { icon: "⏱️", label: "Duration", value: "8–12 days" }, { icon: "⛽", label: "Fuel warning", value: "No pump Batal–Kaza" }, { icon: "🏧", label: "ATM warning", value: "Unreliable in Kaza" }],
  },
  { name: "Vaishno Devi", slug: "vaishno-devi", info: "1,584m · J&K", note: "India's most visited shrine", temp: "18°🌤️", image: "/vaishno-devi.jpg", grad: "linear-gradient(150deg,#5a1a1a,#7a3030 60%,#5a2020)", rot: -1, color: "#be123c", type: "pilgrimage" as const, activities: ["trekking", "pilgrimage"] as string[],
    wx: { icon: "🌤️", temp: 18, feels: 17, hum: 65, wind: 8, aqi: 45, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "1,584m", sunrise: "5:35 AM", sunset: "7:20 PM",
      forecast: [{ day: "Tomorrow", icon: "🌤️", hi: 24, lo: 14 },{ day: "Thursday", icon: "☀️", hi: 26, lo: 15 },{ day: "Friday", icon: "⛅", hi: 22, lo: 13 }] },
    routes: [
      { route: "Jammu → Katra", status: "open" as const, note: "NH-44, good" },
      { route: "Katra → Bhawan", status: "open" as const, note: "Trek, normal crowd" },
    ],
    packItems: ["Comfortable shoes", "Light jacket", "Rain poncho", "Water bottle", "Power bank", "Cash ₹3K+", "Aadhaar original", "Yatra slip printed"],
    emergency: [{ name: "Shrine Board", number: "1800-180-1988" }, { name: "Katra Police", number: "01991-232500" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "13 km" }, { icon: "⏱️", label: "Duration", value: "2–3 days" }, { icon: "💰", label: "Budget", value: "₹3K–15K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Ladakh", slug: "ladakh", info: "3,524m · Ladakh", note: "Khardung La, Pangong, the ride", temp: "12°☀️", image: "/ladakh.jpg", grad: "linear-gradient(150deg,#1a2a4a,#2a5a7a 60%,#3a3a2a)", rot: 2, color: "#0369a1", type: "adventure" as const, activities: ["road-trip", "biking", "camping"] as string[],
    wx: { icon: "☀️", temp: 12, feels: 9, hum: 20, wind: 10, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Clear sky", alt: "3,524m", sunrise: "5:25 AM", sunset: "7:35 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 20, lo: 3 },{ day: "Thursday", icon: "☀️", hi: 19, lo: 2 },{ day: "Friday", icon: "⛅", hi: 16, lo: 1 }] },
    routes: [
      { route: "Manali → Rohtang", status: "open" as const, note: "Clear" },
      { route: "Rohtang → Baralacha", status: "partial" as const, note: "Patches near Darcha" },
      { route: "Baralacha → Pang", status: "open" as const, note: "Clear" },
      { route: "Pang → Leh", status: "open" as const, note: "Via Tanglang La" },
    ],
    packItems: ["Down jacket", "Thermals ×3", "Riding gloves", "Cash ₹20K+", "Power bank ×2", "Sunscreen SPF50", "Diamox", "Vehicle docs + permit"],
    emergency: [{ name: "Leh Hospital", number: "01982-252014" }, { name: "BRO Helpline", number: "1800-180-6763" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛣️", label: "Manali–Leh", value: "479 km" }, { icon: "⏱️", label: "Duration", value: "10–15 days" }, { icon: "🏔️", label: "Highest pass", value: "Khardung La 5,359m" }, { icon: "⛽", label: "Last fuel", value: "Tandi / Upshi" }],
  },
  { name: "Chopta", slug: "chopta", info: "3,680m · Uttarakhand", note: "gentle trek to highest Shiva temple", temp: "6°⛅", image: "/chopta.jpg", grad: "linear-gradient(150deg,#1a3a2a,#3a6a4a 60%,#2a5a1a)", rot: -0.5, color: "#15803d", type: "adventure" as const, activities: ["trekking", "nature", "camping"] as string[],
    wx: { icon: "⛅", temp: 6, feels: 3, hum: 50, wind: 15, aqi: 35, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Misty", alt: "3,680m", sunrise: "5:40 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "⛅", hi: 12, lo: 1 },{ day: "Thursday", icon: "🌧️", hi: 8, lo: -1 },{ day: "Friday", icon: "⛅", hi: 10, lo: 0 }] },
    routes: [
      { route: "Rishikesh → Ukhimath", status: "open" as const, note: "Via Rudraprayag" },
      { route: "Ukhimath → Chopta", status: "open" as const, note: "Scenic road" },
      { route: "Chopta → Tungnath", status: "open" as const, note: "3.5 km trek" },
    ],
    packItems: ["Fleece jacket", "Trekking shoes", "Rain poncho", "Water bottle", "Power bank", "Cash ₹5K+", "Sunscreen", "First aid kit"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Ukhimath PHC", number: "01364-240235" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "3.5 km" }, { icon: "⏱️", label: "Duration", value: "3–4 days" }, { icon: "💰", label: "Budget", value: "₹4K–12K" }, { icon: "🏔️", label: "Tungnath alt.", value: "3,680m" }],
  },
  { name: "Badrinath", slug: "badrinath", info: "3,133m · Uttarakhand", note: "easiest Char Dham, drive-to temple", temp: "10°⛅", image: "/badrinath.jpg", grad: "linear-gradient(150deg,#2d1060,#4a2080 60%,#6a3060)", rot: 1, color: "#6d28d9", type: "pilgrimage" as const, activities: ["pilgrimage", "road-trip"] as string[],
    wx: { icon: "⛅", temp: 10, feels: 7, hum: 45, wind: 15, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Partly cloudy", alt: "3,133m", sunrise: "5:38 AM", sunset: "7:02 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 14, lo: 3 },{ day: "Thursday", icon: "⛅", hi: 12, lo: 2 },{ day: "Friday", icon: "🌧️", hi: 9, lo: 1 }] },
    routes: [
      { route: "Rishikesh → Joshimath", status: "open" as const, note: "NH-7, 250 km" },
      { route: "Joshimath → Badrinath", status: "open" as const, note: "45 km" },
      { route: "Badrinath → Mana Village", status: "open" as const, note: "3 km walk" },
    ],
    packItems: ["Warm jacket", "Thermals", "Walking shoes", "Towel for Tapt Kund", "Cash ₹5K+", "E-pass printed", "Power bank", "First aid kit"],
    emergency: [{ name: "Badrinath PHC", number: "01381-222226" }, { name: "SDRF Uttarakhand", number: "1070" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛕", label: "Temple type", value: "Char Dham" }, { icon: "🚗", label: "From Rishikesh", value: "295 km" }, { icon: "💰", label: "Budget", value: "₹3K–20K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Rishikesh", slug: "rishikesh", info: "372m · Uttarakhand", note: "gateway to the Himalayas", temp: "28°☀️", image: "/rishikesh.jpg", grad: "linear-gradient(150deg,#064e3b,#059669 60%,#0d9488)", rot: -1.5, color: "#059669", type: "adventure" as const, activities: ["rafting", "camping", "yoga"] as string[],
    wx: { icon: "☀️", temp: 28, feels: 30, hum: 60, wind: 8, aqi: 55, aqiLabel: "Moderate", aqiColor: "#f59e0b", cond: "Sunny", alt: "372m", sunrise: "5:35 AM", sunset: "7:05 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 32, lo: 22 },{ day: "Thursday", icon: "⛅", hi: 30, lo: 21 },{ day: "Friday", icon: "☀️", hi: 33, lo: 23 }] },
    routes: [
      { route: "Dehradun → Rishikesh", status: "open" as const, note: "43 km, 1 hr" },
      { route: "Delhi → Rishikesh", status: "open" as const, note: "240 km, 5–6 hrs" },
      { route: "Rishikesh → Rudraprayag", status: "open" as const, note: "NH-7, 140 km" },
    ],
    packItems: ["Cash (full trip budget)", "E-pass printed", "Trekking shoes", "Rain gear", "Power bank", "Offline maps", "Diamox", "First aid kit"],
    emergency: [{ name: "AIIMS Rishikesh", number: "0135-2462930" }, { name: "Rishikesh Police", number: "0135-2430245" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏧", label: "ATMs", value: "20+ reliable" }, { icon: "🚣", label: "Rafting", value: "₹800–1,500" }, { icon: "🧘", label: "Yoga", value: "Ashrams available" }, { icon: "🛣️", label: "To Kedarnath", value: "248 km" }],
  },
  { name: "Valley of Flowers", slug: "valley-of-flowers", info: "3,658m · Uttarakhand", note: "UNESCO trek, 500+ wildflower species", temp: "10°🌧️", image: "/valley-of-flowers.jpg", grad: "linear-gradient(150deg,#4a1060,#86198f 60%,#c026d3)", rot: 0.5, color: "#86198f", type: "adventure" as const, activities: ["trekking", "nature"] as string[],
    wx: { icon: "🌧️", temp: 10, feels: 7, hum: 85, wind: 10, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Monsoon bloom", alt: "3,658m", sunrise: "5:40 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "🌧️", hi: 12, lo: 5 },{ day: "Thursday", icon: "⛅", hi: 14, lo: 4 },{ day: "Friday", icon: "🌧️", hi: 10, lo: 3 }] },
    routes: [
      { route: "Rishikesh → Govindghat", status: "open" as const, note: "270 km, 9–10 hrs" },
      { route: "Govindghat → Ghangaria", status: "open" as const, note: "14 km trek" },
      { route: "Ghangaria → Valley", status: "open" as const, note: "3 km trail" },
    ],
    packItems: ["Waterproof shoes", "Rain jacket", "Leech socks", "Warm fleece", "Cash ₹5K–8K", "Camera", "Power bank", "Diamox"],
    emergency: [{ name: "Joshimath Hospital", number: "01389-222215" }, { name: "SDRF Uttarakhand", number: "1070" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🌸", label: "Species", value: "500+" }, { icon: "📅", label: "Best month", value: "August" }, { icon: "🎫", label: "Entry fee", value: "₹750" }, { icon: "🥾", label: "Trek", value: "17 km" }],
  },
  { name: "Manali", slug: "manali", info: "2,050m · Himachal Pradesh", note: "gateway to Ladakh and Spiti", temp: "18°🌤️", image: "/manali.jpg", grad: "linear-gradient(150deg,#1a3a5a,#2a6a4a 60%,#3a4a2a)", rot: -0.5, color: "#2563eb", type: "adventure" as const, activities: ["road-trip", "rafting", "biking", "camping"] as string[],
    wx: { icon: "🌤️", temp: 18, feels: 16, hum: 50, wind: 10, aqi: 30, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "2,050m", sunrise: "5:40 AM", sunset: "7:10 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 22, lo: 8 },{ day: "Thursday", icon: "⛅", hi: 20, lo: 7 },{ day: "Friday", icon: "🌧️", hi: 16, lo: 6 }] },
    routes: [
      { route: "Dehradun → Manali", status: "open" as const, note: "530 km, 10-12 hrs" },
      { route: "Manali → Leh", status: "open" as const, note: "479 km (Jun-Oct)" },
      { route: "Manali → Rohtang", status: "open" as const, note: "51 km" },
    ],
    packItems: ["Warm jacket", "Rain gear", "Fuel cans (if biking north)", "Cash ₹15K+", "Power bank", "Offline maps", "First aid kit"],
    emergency: [{ name: "Manali Hospital", number: "01902-252375" }, { name: "Manali Police", number: "01902-252126" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏍️", label: "To Leh", value: "479 km" }, { icon: "🎿", label: "Solang Valley", value: "14 km" }, { icon: "💰", label: "Budget", value: "₹3K-15K" }, { icon: "📅", label: "Best month", value: "September" }],
  },
  { name: "Shimla", slug: "shimla", info: "2,206m · Himachal Pradesh", note: "colonial hill station, Spiti gateway", temp: "15°🌤️", image: "/shimla.jpg", grad: "linear-gradient(150deg,#4a2020,#8a4040 60%,#6a3030)", rot: 1, color: "#dc2626", type: "adventure" as const, activities: ["road-trip", "nature"] as string[],
    wx: { icon: "🌤️", temp: 15, feels: 13, hum: 55, wind: 12, aqi: 40, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "2,206m", sunrise: "5:38 AM", sunset: "7:08 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 20, lo: 8 },{ day: "Thursday", icon: "⛅", hi: 18, lo: 7 },{ day: "Friday", icon: "🌧️", hi: 14, lo: 6 }] },
    routes: [
      { route: "Dehradun → Shimla", status: "open" as const, note: "245 km, 5.5 hrs" },
      { route: "Shimla → Reckong Peo", status: "open" as const, note: "220 km, NH-5" },
      { route: "Shimla → Kaza (Spiti)", status: "open" as const, note: "415 km, 2 days" },
    ],
    packItems: ["Warm jacket", "Rain gear", "Cash ₹20K+ for Spiti", "Fuel for onward", "Offline maps", "Diamox", "Dry snacks"],
    emergency: [{ name: "IGMC Hospital", number: "0177-2804251" }, { name: "Shimla Police", number: "0177-2812344" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🚂", label: "Toy train", value: "Kalka-Shimla" }, { icon: "🛣️", label: "To Kaza", value: "415 km" }, { icon: "💰", label: "Budget", value: "₹2.5K-12K" }, { icon: "📅", label: "Best months", value: "Sep-Oct" }],
  },
  { name: "Dharamshala & McLeodganj", slug: "dharamshala", info: "1,457m · Himachal Pradesh", note: "Triund trek and Tibetan quarter", temp: "18°🌤️", image: "/dharamshala.jpg", grad: "linear-gradient(150deg,#1f3a2d,#3a6a4a 60%,#5a8a6a)", rot: -1, color: "#16a34a", type: "adventure" as const, activities: ["trekking", "camping", "yoga", "nature"] as string[],
    wx: { icon: "🌤️", temp: 18, feels: 16, hum: 60, wind: 8, aqi: 35, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "1,457m", sunrise: "5:42 AM", sunset: "7:05 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 22, lo: 10 },{ day: "Thursday", icon: "⛅", hi: 20, lo: 9 },{ day: "Friday", icon: "🌧️", hi: 16, lo: 8 }] },
    routes: [
      { route: "Dehradun → Dharamshala", status: "open" as const, note: "270 km, 6-7 hrs" },
      { route: "Dharamshala → McLeodganj", status: "open" as const, note: "10 km uphill" },
      { route: "McLeodganj → Triund", status: "open" as const, note: "9 km trek, 4-5 hrs" },
    ],
    packItems: ["Trekking shoes", "Headlamp", "Fleece mid-layer", "Rain shell", "Trekking poles", "Cash ₹3K+", "Tent (for overnight)"],
    emergency: [{ name: "Dharamshala Hospital", number: "01892-222037" }, { name: "McLeodganj Police", number: "01892-221483" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Triund trek", value: "9 km" }, { icon: "⛰️", label: "Triund altitude", value: "2,842m" }, { icon: "💰", label: "Budget", value: "₹2K-12K" }, { icon: "📅", label: "Best months", value: "Sep-Nov" }],
  },
  { name: "Hemkund Sahib", slug: "hemkund-sahib", info: "4,329m · Uttarakhand", note: "world's highest Gurudwara", temp: "4°🌨️", image: "/hemkund-sahib.jpg", grad: "linear-gradient(150deg,#1a2540,#3a5a8a 60%,#5a8aaa)", rot: 2, color: "#1d4ed8", type: "pilgrimage" as const, activities: ["pilgrimage", "trekking"] as string[],
    wx: { icon: "🌨️", temp: 4, feels: 0, hum: 70, wind: 18, aqi: 25, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cold", alt: "4,329m", sunrise: "5:38 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "⛅", hi: 8, lo: 0 },{ day: "Thursday", icon: "🌨️", hi: 5, lo: -2 },{ day: "Friday", icon: "❄️", hi: 4, lo: -3 }] },
    routes: [
      { route: "Dehradun → Govindghat", status: "open" as const, note: "290 km, 8-9 hrs" },
      { route: "Govindghat → Ghangaria", status: "open" as const, note: "13 km trek / pony / helicopter" },
      { route: "Ghangaria → Hemkund Sahib", status: "open" as const, note: "6 km, 3-4 hrs trek" },
    ],
    packItems: ["Headlamp", "Down jacket", "Trekking poles", "Cash ₹5K+", "Sunscreen SPF 50+", "Gaiters (Jun snow)", "2L water"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Joshimath Hospital", number: "01389-222019" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏔️", label: "Altitude", value: "4,329m" }, { icon: "🥾", label: "Trek", value: "6 km from Ghangaria" }, { icon: "📅", label: "Season", value: "Late May-Oct" }, { icon: "🆓", label: "Permit", value: "None required" }],
  },
  { name: "Gangotri", slug: "gangotri", info: "3,048m · Uttarakhand", note: "3rd Char Dham, Gaumukh glacier base", temp: "8°🌥️", image: "/gangotri.jpg", grad: "linear-gradient(150deg,#2a2a4a,#4a4a6a 60%,#6a6a8a)", rot: -1.5, color: "#4338ca", type: "pilgrimage" as const, activities: ["pilgrimage", "trekking"] as string[],
    wx: { icon: "🌥️", temp: 8, feels: 5, hum: 60, wind: 14, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool", alt: "3,048m", sunrise: "5:40 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "⛅", hi: 14, lo: 2 },{ day: "Thursday", icon: "🌥️", hi: 12, lo: 1 },{ day: "Friday", icon: "🌧️", hi: 9, lo: 0 }] },
    routes: [
      { route: "Dehradun → Uttarkashi", status: "open" as const, note: "174 km, 5-6 hrs" },
      { route: "Uttarkashi → Gangotri", status: "open" as const, note: "100 km, 3-4 hrs" },
      { route: "Gangotri → Gaumukh", status: "open" as const, note: "19 km trek, 2 days" },
    ],
    packItems: ["Down jacket", "Thermals", "Trekking shoes", "Char Dham e-pass", "Gaumukh permit", "Cash ₹5K+ (Uttarkashi ATM)", "Headlamp"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Uttarkashi Hospital", number: "01374-222213" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏔️", label: "Altitude", value: "3,048m" }, { icon: "🥾", label: "Gaumukh trek", value: "19 km" }, { icon: "📋", label: "Permit", value: "Rs 150/day (150 cap)" }, { icon: "📅", label: "Best months", value: "Sep-Oct" }],
  },
  { name: "Yamunotri", slug: "yamunotri", info: "3,293m · Uttarakhand", note: "1st Char Dham, Surya Kund hot spring", temp: "10°🌤️", image: "/yamunotri.jpg", grad: "linear-gradient(150deg,#5a2a1a,#8a5a2a 60%,#aa7a3a)", rot: 1.5, color: "#ea580c", type: "pilgrimage" as const, activities: ["pilgrimage", "trekking"] as string[],
    wx: { icon: "🌤️", temp: 10, feels: 7, hum: 55, wind: 12, aqi: 30, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool", alt: "3,293m", sunrise: "5:42 AM", sunset: "7:02 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 16, lo: 4 },{ day: "Thursday", icon: "⛅", hi: 14, lo: 3 },{ day: "Friday", icon: "🌧️", hi: 11, lo: 2 }] },
    routes: [
      { route: "Dehradun → Barkot", status: "open" as const, note: "155 km, 4-5 hrs via Mussoorie" },
      { route: "Barkot → Janki Chatti", status: "open" as const, note: "20 km, 45 min" },
      { route: "Janki Chatti → Yamunotri", status: "open" as const, note: "6 km trek (walk/pony only)" },
    ],
    packItems: ["Trekking shoes (wet stone)", "Rain poncho", "Jacket (3,293m)", "Char Dham e-pass", "GMOU green card", "Cash ₹3K+ (Barkot ATM)", "Water 1.5L"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Barkot Police", number: "01375-222226" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏔️", label: "Altitude", value: "3,293m" }, { icon: "🥾", label: "Trek", value: "6 km from Janki Chatti" }, { icon: "🚁", label: "Helicopter", value: "None (everyone walks)" }, { icon: "📅", label: "Best months", value: "May, Sep-Oct" }],
  },
  { name: "Amarnath", slug: "amarnath", info: "3,888m · Jammu & Kashmir", note: "cave shrine, SASB yatra Jul-Aug", temp: "6°❄️", image: "/amarnath.jpg", grad: "linear-gradient(150deg,#2a3045,#4a5070 60%,#6a7090)", rot: -1, color: "#475569", type: "pilgrimage" as const, activities: ["pilgrimage", "trekking"] as string[],
    wx: { icon: "❄️", temp: 6, feels: 2, hum: 65, wind: 16, aqi: 25, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cold", alt: "3,888m", sunrise: "5:36 AM", sunset: "7:14 PM",
      forecast: [{ day: "Tomorrow", icon: "🌨️", hi: 10, lo: 1 },{ day: "Thursday", icon: "❄️", hi: 7, lo: 0 },{ day: "Friday", icon: "🌧️", hi: 8, lo: 2 }] },
    routes: [
      { route: "Dehradun → Srinagar (flight)", status: "open" as const, note: "1.5 hrs, Rs 3.5K-5.5K" },
      { route: "Srinagar → Baltal", status: "open" as const, note: "93 km, 2-2.5 hrs" },
      { route: "Baltal → Amarnath Cave", status: "open" as const, note: "14 km trek, 1 day" },
      { route: "Pahalgam → Amarnath Cave", status: "open" as const, note: "46 km, 3-4 days" },
    ],
    packItems: ["SASB Yatra Parchi", "Medical certificate (SASB format)", "Headlamp", "Thermals", "Rain poncho", "Trekking shoes", "Cash ₹5-7K (Pahalgam ATM)"],
    emergency: [{ name: "SASB Helpline", number: "0194-2313146" }, { name: "CRPF Yatra Control", number: "0194-2455202" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏔️", label: "Cave altitude", value: "3,888m" }, { icon: "📋", label: "Registration", value: "SASB mandatory" }, { icon: "🩺", label: "Medical cert", value: "Required" }, { icon: "📅", label: "Season", value: "Jul-Aug (40-60 days)" }],
  },
  { name: "Nainital & Mukteshwar", slug: "nainital", info: "2,084m · Uttarakhand (Kumaon)", note: "Naini Lake, Mukteshwar apple country", temp: "16°⛅", image: "/nainital.jpg", grad: "linear-gradient(150deg,#1a3a5a,#3a5a7a 60%,#5a7a9a)", rot: 0.5, color: "#0284c7", type: "adventure" as const, activities: ["road-trip", "nature", "camping"] as string[],
    wx: { icon: "⛅", temp: 16, feels: 14, hum: 60, wind: 8, aqi: 38, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "2,084m", sunrise: "5:42 AM", sunset: "7:08 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 22, lo: 10 },{ day: "Thursday", icon: "⛅", hi: 20, lo: 9 },{ day: "Friday", icon: "🌧️", hi: 18, lo: 8 }] },
    routes: [
      { route: "Dehradun → Nainital", status: "open" as const, note: "310 km via Haridwar-Rampur, 6-7 hrs" },
      { route: "Delhi → Nainital", status: "open" as const, note: "300 km via NH9, 6-7 hrs" },
      { route: "Nainital → Mukteshwar", status: "open" as const, note: "51 km via Bhimtal, 1.5-2 hrs" },
      { route: "Nainital → Jim Corbett", status: "open" as const, note: "65 km via Ramnagar" },
    ],
    packItems: ["Light fleece / jacket", "Walking shoes", "Cash ₹3K+", "ID for hotel check-in", "Rain poncho (Jul-Sep)", "Binoculars (Corbett)", "Thermals (Nov-Feb)"],
    emergency: [{ name: "Nainital District Hospital", number: "05942-235012" }, { name: "Nainital Police", number: "05942-235424" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏞️", label: "Naini Lake", value: "1.5 km long" }, { icon: "🐅", label: "Corbett", value: "65 km away" }, { icon: "💰", label: "Budget", value: "₹4K-12K" }, { icon: "📅", label: "Best months", value: "Oct-Nov, Mar-Jun" }],
  },
  { name: "Auli", slug: "auli", info: "3,049m · Uttarakhand", note: "India's best ski destination, Nanda Devi views", temp: "2°❄️", image: "/auli.jpg", grad: "linear-gradient(150deg,#1a2540,#3a4a7a 60%,#5a6a9a)", rot: -1, color: "#0ea5e9", type: "adventure" as const, activities: ["road-trip", "trekking", "camping"] as string[],
    wx: { icon: "❄️", temp: 2, feels: -3, hum: 55, wind: 15, aqi: 25, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cold", alt: "3,049m", sunrise: "5:42 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "🌨️", hi: 6, lo: -2 },{ day: "Thursday", icon: "❄️", hi: 4, lo: -4 },{ day: "Friday", icon: "⛅", hi: 8, lo: -1 }] },
    routes: [
      { route: "Dehradun → Joshimath", status: "open" as const, note: "295 km via Rishikesh, 8-10 hrs" },
      { route: "Joshimath → Auli (gondola)", status: "open" as const, note: "4.15 km, Rs 1,000 return" },
      { route: "Joshimath → Auli (road)", status: "open" as const, note: "14 km, 45 min taxi" },
      { route: "Auli → Gorson Bugyal", status: "open" as const, note: "3 km trail, 2-3 hrs" },
    ],
    packItems: ["Ski jacket (-10C)", "Thermals", "Waterproof pants", "Gloves (cold)", "Ski goggles", "Wool socks", "Sunscreen SPF 50+"],
    emergency: [{ name: "GMVN Auli Office", number: "01389-222220" }, { name: "Joshimath Hospital", number: "01389-222019" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "⛷️", label: "Top altitude", value: "3,049m" }, { icon: "🚠", label: "Cable car", value: "4.15 km" }, { icon: "🎿", label: "Equipment", value: "Rs 500-800/day" }, { icon: "📅", label: "Ski months", value: "Jan-Feb" }],
  },
  { name: "Har Ki Dun", slug: "har-ki-dun", info: "3,566m · Uttarakhand", note: "underrated valley trek, Govind Sanctuary", temp: "8°⛅", image: "/har-ki-dun.jpg", grad: "linear-gradient(150deg,#1f3a2a,#3a6a4a 60%,#5a8a6a)", rot: 1, color: "#16a34a", type: "adventure" as const, activities: ["trekking", "camping", "nature"] as string[],
    wx: { icon: "⛅", temp: 8, feels: 5, hum: 60, wind: 10, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool", alt: "3,566m", sunrise: "5:40 AM", sunset: "7:02 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 12, lo: 2 },{ day: "Thursday", icon: "⛅", hi: 10, lo: 1 },{ day: "Friday", icon: "🌧️", hi: 8, lo: 0 }] },
    routes: [
      { route: "Dehradun → Sankri", status: "open" as const, note: "180 km via Mussoorie-Purola, 5-6 hrs" },
      { route: "Sankri → Taluka", status: "open" as const, note: "11 km jeep road, Rs 1K-1.5K" },
      { route: "Taluka → Seema → Osla", status: "open" as const, note: "14 km trek through forest" },
      { route: "Osla → Har Ki Dun", status: "open" as const, note: "10 km, 4-5 hrs, glacier views" },
    ],
    packItems: ["Trekking shoes", "Sleeping bag -5C", "Govind permit", "Cash ₹5K+", "Power bank 20K mAh", "Water purifier", "Rain poncho"],
    emergency: [{ name: "Sankri Forest Office", number: "01373-272201" }, { name: "Uttarkashi Hospital", number: "01374-222213" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏔️", label: "Valley altitude", value: "3,566m" }, { icon: "🥾", label: "Trek", value: "24 km one way" }, { icon: "🛕", label: "Cultural", value: "Duryodhana temple at Osla" }, { icon: "📅", label: "Best months", value: "May-Jun, Sep-Oct" }],
  },
  { name: "Roopkund", slug: "roopkund", info: "5,029m · Uttarakhand", note: "skeleton lake, 8-day high-altitude trek", temp: "-2°❄️", image: "/roopkund.jpg", grad: "linear-gradient(150deg,#1a2030,#2a3548 60%,#4a5870)", rot: -1.5, color: "#475569", type: "adventure" as const, activities: ["trekking", "camping"] as string[],
    wx: { icon: "❄️", temp: -2, feels: -8, hum: 65, wind: 20, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Very cold", alt: "5,029m", sunrise: "5:38 AM", sunset: "7:04 PM",
      forecast: [{ day: "Tomorrow", icon: "❄️", hi: 2, lo: -8 },{ day: "Thursday", icon: "🌨️", hi: 0, lo: -10 },{ day: "Friday", icon: "❄️", hi: -2, lo: -12 }] },
    routes: [
      { route: "Dehradun → Lohajung", status: "open" as const, note: "260 km via Rishikesh-Chamoli, 8-9 hrs" },
      { route: "Lohajung → Ali Bugyal", status: "open" as const, note: "17 km via Didna, 2 days" },
      { route: "Bedni Bugyal → Bhaguabasa", status: "open" as const, note: "9 km via Patar Nachauni" },
      { route: "Bhaguabasa → Roopkund", status: "open" as const, note: "Fixed-rope summit push, 4-5 hrs" },
    ],
    packItems: ["Sleeping bag -10C", "Down jacket", "Thermals x2", "Crampons (May-Jun)", "Pulse oximeter", "Headlamp", "Cash ₹5K+", "Power bank 20K mAh"],
    emergency: [{ name: "Lohajung Forest Office", number: "01386-256221" }, { name: "Chamoli Hospital", number: "01372-252335" }, { name: "SDRF Uttarakhand", number: "1070" }],
    quickFacts: [{ icon: "🏔️", label: "Lake altitude", value: "5,029m" }, { icon: "💀", label: "Skeletons", value: "800-1,200 around rim" }, { icon: "⚠️", label: "Difficulty", value: "Hard" }, { icon: "📅", label: "Best months", value: "Sep-Oct" }],
  },
  { name: "Sandakphu", slug: "sandakphu", info: "3,636m · West Bengal", note: "4 of world's 5 highest peaks from one point", temp: "6°⛅", image: "/sandakphu.jpg", grad: "linear-gradient(150deg,#1a3540,#3a6580 60%,#6a95b0)", rot: 1.5, color: "#0891b2", type: "adventure" as const, activities: ["trekking"] as string[],
    wx: { icon: "⛅", temp: 6, feels: 3, hum: 70, wind: 18, aqi: 30, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool clear", alt: "3,636m", sunrise: "5:00 AM", sunset: "6:30 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 10, lo: 2 },{ day: "Thursday", icon: "⛅", hi: 8, lo: 1 },{ day: "Friday", icon: "🌥️", hi: 7, lo: 0 }] },
    routes: [
      { route: "Dehradun → Bagdogra (flight)", status: "open" as const, note: "1.5 hrs, Rs 3K-8K" },
      { route: "Bagdogra → Darjeeling", status: "open" as const, note: "70 km, 3-4 hrs" },
      { route: "Darjeeling → Manebhanjang", status: "open" as const, note: "26 km, 1.5 hrs" },
      { route: "Manebhanjang → Sandakphu", status: "open" as const, note: "32 km trek (4 days) or Land Rover (4.5 hrs)" },
    ],
    packItems: ["Waterproof trekking shoes", "Insulated jacket", "Thermals", "Headlamp (4:45 AM start)", "Singalila NP permit", "Cash ₹6K+", "Rain poncho"],
    emergency: [{ name: "Singalila NP Office", number: "0354-2240107" }, { name: "Darjeeling Hospital", number: "0354-2254328" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🌄", label: "4 of 5 highest", value: "Everest, Kanchenjunga, Lhotse, Makalu" }, { icon: "🚙", label: "Land Rover option", value: "32 km in 4.5 hrs" }, { icon: "👤", label: "Guide", value: "Compulsory in park" }, { icon: "📅", label: "Best months", value: "Oct-Nov" }],
  },
  { name: "Kasol & Kheerganga", slug: "kasol", info: "1,574m · Himachal Pradesh", note: "Parvati Valley, Kheerganga trek, Manikaran springs", temp: "12°⛅", image: "/kasol.jpg", grad: "linear-gradient(150deg,#1a3a2a,#2a5a3a 60%,#4a7a5a)", rot: -1, color: "#15803d", type: "adventure" as const, activities: ["trekking", "camping", "nature"] as string[],
    wx: { icon: "⛅", temp: 12, feels: 10, hum: 65, wind: 8, aqi: 32, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool", alt: "1,574m", sunrise: "5:45 AM", sunset: "7:05 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 18, lo: 7 },{ day: "Thursday", icon: "⛅", hi: 16, lo: 6 },{ day: "Friday", icon: "🌧️", hi: 14, lo: 5 }] },
    routes: [
      { route: "Dehradun → Kasol", status: "open" as const, note: "360 km via Chandigarh-Mandi-Bhuntar, 8-9 hrs" },
      { route: "Bhuntar → Kasol", status: "open" as const, note: "30 km, 45-60 min, Rs 50-80 bus" },
      { route: "Kasol → Manikaran", status: "open" as const, note: "4 km, 15 min" },
      { route: "Barshaini → Kheerganga", status: "open" as const, note: "12 km trek, 4-5 hrs up" },
    ],
    packItems: ["Trekking shoes", "Sleeping bag 0C", "30-35L daypack", "Thermal base layer", "Headlamp", "Power bank", "Cash ₹3K+ (Bhuntar ATM)", "Quick-dry towel"],
    emergency: [{ name: "Kasol Police Post", number: "01902-273010" }, { name: "Kullu District Hospital", number: "01902-222359" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "♨️", label: "Kheerganga", value: "2,960m hot spring pool" }, { icon: "🔥", label: "Manikaran springs", value: "88-95°C" }, { icon: "🥾", label: "Trek", value: "12 km from Barshaini" }, { icon: "📅", label: "Best months", value: "Mar-Jun, Sep-Nov" }],
  },
  { name: "Tirthan Valley", slug: "tirthan-valley", info: "1,885m · Himachal Pradesh", note: "GHNP UNESCO, Serolsar Lake trek, trout fishing", temp: "14°⛅", image: "/tirthan-valley.jpg", grad: "linear-gradient(150deg,#2a3a1f,#4a5a2a 60%,#6a8a4a)", rot: 1, color: "#65a30d", type: "adventure" as const, activities: ["trekking", "nature", "camping"] as string[],
    wx: { icon: "⛅", temp: 14, feels: 12, hum: 60, wind: 6, aqi: 30, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "1,885m", sunrise: "5:48 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 20, lo: 9 },{ day: "Thursday", icon: "⛅", hi: 18, lo: 8 },{ day: "Friday", icon: "🌧️", hi: 16, lo: 7 }] },
    routes: [
      { route: "Dehradun → Banjaar", status: "open" as const, note: "340 km via Chandigarh-Larji, 8-9 hrs" },
      { route: "Larji junction → Banjaar", status: "open" as const, note: "50 km, 1.5 hrs (left turn!)" },
      { route: "Banjaar → Jalori Pass", status: "open" as const, note: "30 km, 1.5 hrs (Jun-Oct only)" },
      { route: "Jalori Pass → Serolsar Lake", status: "open" as const, note: "6 km trek, 1.5-2 hrs" },
    ],
    packItems: ["Walking shoes (forest paths)", "Mid-layer fleece", "Rain poncho", "Binoculars (birding)", "GHNP permit", "Cash ₹5K+ (Kullu ATM)", "Fishing license (if fishing)"],
    emergency: [{ name: "GHNP Reception Sai Ropa", number: "01903-225014" }, { name: "Banjaar Police", number: "01903-265008" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🌲", label: "GHNP", value: "754 sq km UNESCO" }, { icon: "🐟", label: "Trout fishing", value: "Mar-Jun, Sep-Nov" }, { icon: "🏔️", label: "Jalori Pass", value: "3,120m" }, { icon: "📅", label: "Best months", value: "Apr-Jun, Sep-Oct" }],
  },
  { name: "Lachung & Yumthang", slug: "lachung", info: "2,680m · Sikkim", note: "North Sikkim rhododendron valley, Zero Point 4,428m", temp: "8°🌥️", image: "/lachung.jpg", grad: "linear-gradient(150deg,#1a3a4a,#2a5a6a 60%,#4a7a8a)", rot: -1.5, color: "#0e7490", type: "adventure" as const, activities: ["road-trip", "nature", "trekking"] as string[],
    wx: { icon: "🌥️", temp: 8, feels: 5, hum: 70, wind: 12, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Cool cloudy", alt: "2,680m", sunrise: "5:00 AM", sunset: "6:30 PM",
      forecast: [{ day: "Tomorrow", icon: "⛅", hi: 12, lo: 3 },{ day: "Thursday", icon: "🌧️", hi: 10, lo: 2 },{ day: "Friday", icon: "🌥️", hi: 11, lo: 3 }] },
    routes: [
      { route: "Dehradun → Bagdogra (flight)", status: "open" as const, note: "1.5 hrs, Rs 3K-8K" },
      { route: "Bagdogra → Gangtok", status: "open" as const, note: "100 km, 3.5-4 hrs, Rs 250/seat" },
      { route: "Gangtok → Lachung", status: "open" as const, note: "115 km, 4-5 hrs (registered vehicle)" },
      { route: "Lachung → Yumthang → Zero Point", status: "open" as const, note: "47 km, day trip" },
    ],
    packItems: ["ILP permit (Aadhaar + 2 photos)", "Insulated windproof jacket", "Thermals", "Waterproof trekking shoes", "Cash ₹8-10K (no ATM beyond Gangtok)", "Power bank", "Offline maps"],
    emergency: [{ name: "Sikkim Tourism Gangtok", number: "03592-221634" }, { name: "Mangan Hospital", number: "03592-234047" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🌸", label: "Rhododendrons", value: "36 species, Apr-May peak" }, { icon: "❄️", label: "Zero Point", value: "4,428m year-round snow" }, { icon: "📋", label: "ILP", value: "Same-day at MG Marg" }, { icon: "📅", label: "Peak bloom", value: "2nd-3rd week April" }],
  },
];

export const SEARCH_DESTINATIONS = [
  ...DESTINATIONS.map(d => ({ name: d.name, slug: d.slug, info: d.info, color: d.color, type: d.type, activities: d.activities })),
];

export const ACTIVITIES = [
  { key: "trekking", label: "Trekking", icon: "🥾" },
  { key: "pilgrimage", label: "Pilgrimage", icon: "🙏" },
  { key: "road-trip", label: "Road trip", icon: "🛣️" },
  { key: "camping", label: "Camping", icon: "⛺" },
  { key: "nature", label: "Nature & wildlife", icon: "🌿" },
  { key: "rafting", label: "Rafting", icon: "🚣" },
  { key: "biking", label: "Biking", icon: "🏍️" },
  { key: "yoga", label: "Yoga & wellness", icon: "🧘" },
] as const;

export const GUIDES = [
  { slug: "acclimatize-above-3000m", title: "How to acclimatize above 3,000m - AMS, Diamox and ascent rules", tag: "Health", min: 14, rot: -1.5, href: "/guides/acclimatize-above-3000m", desc: "Practical acclimatization guide for treks above 3,000m in India. Altitude sickness symptoms, Diamox dosage and timing, safe ascent rates, hydration, and when to descend. Written from Dehradun." },
  { slug: "best-time-char-dham", title: "Best time to visit Char Dham - Kedarnath, Badrinath, Gangotri, Yamunotri", tag: "Planning", min: 16, rot: 1, href: "/guides/best-time-char-dham", desc: "Temple opening dates, month-by-month conditions, crowd windows, helicopter availability, and the honest case for September-October over May. Written from Dehradun." },
  { slug: "packing-4000m", title: "What to pack for 4,000m+ altitude treks in India", tag: "Packing", min: 18, rot: -0.5, href: "/guides/packing-4000m", desc: "The 3-layer clothing system, summer vs late-season gear lists, weight targets under 8 kg, and where to buy everything in Dehradun. Written from experience." },
  { slug: "monsoon-routes", title: "Monsoon travel: which mountain routes to avoid", tag: "Safety", min: 4, rot: -1, href: "/guides/monsoon-routes", desc: "Landslide-prone zones, BRO repair schedules, and safe alternatives during July–September." },
  { slug: "atm-cash-guide", title: "ATM and cash guide for remote Himalayan towns", tag: "Money", min: 20, rot: 0.8, href: "/guides/atm-cash-guide", desc: "Town-by-town ATM reliability, UPI dead zones, network coverage, and cash carry recommendations for Char Dham, Spiti, Ladakh and Vaishno Devi routes. Written from Dehradun." },
  { slug: "char-dham-epass", title: "Char Dham e-pass and permits - how to register online (2026)", tag: "Documents", min: 22, rot: -0.8, href: "/guides/char-dham-epass", desc: "Step-by-step Char Dham registration, daily pilgrim caps, Spiti ILP, Rohtang permit, and Ladakh PAP. Common rejection reasons and what to do. Written from Dehradun." },
  { slug: "kedarnath-budget", title: "Kedarnath trip under Rs 8,000 - a day-by-day budget breakdown", tag: "Budget", min: 18, rot: 1.2, href: "/guides/kedarnath-budget", desc: "Complete day-by-day cost split from Rishikesh to Kedarnath and back. Transport, food, accommodation, and helicopter comparison. 2026 season prices." },
  { slug: "dehradun-to-kedarnath", title: "Dehradun to Kedarnath: Distance, Route & Travel Time", tag: "Planning", min: 14, rot: -0.6, href: "/guides/dehradun-to-kedarnath", desc: "Dehradun to Kedarnath is 245 km by road to Gaurikund, then an 18 km trek. Full route breakdown, transport options, Sonprayag barrier, and costs from Dehradun." },
  { slug: "kedarnath-opening-date-2026", title: "Kedarnath Opening Date 2026: When Does the Temple Open & Close?", tag: "Planning", min: 14, rot: 0.4, href: "/guides/kedarnath-opening-date-2026", desc: "Kedarnath temple opens April 30, 2026 (Akshaya Tritiya). Opening ceremony, historical dates table, temple timings, closing date, and month-by-month crowd guide." },
  { slug: "manali-to-spiti-valley", title: "Manali to Spiti Valley: Complete Route Guide 2026", tag: "Planning", min: 19, rot: -1.1, href: "/guides/manali-to-spiti-valley", desc: "190 km, one pass at 4,590m, zero ATMs. Atal Tunnel vs Rohtang, Gramphoo junction, Batal, Kunzum Pass, Chandrataal detour, and the fuel gap explained." },
] as const;

export const GEAR = [
  { ic: "🥾", type: "Trekking shoes", name: "Quechua MH500", price: "₹3,999", link: "Amazon", rot: -0.8 },
  { ic: "🧥", type: "Windproof jacket", name: "Forclaz MT500", price: "₹4,999", link: "Decathlon", rot: 1.2 },
  { ic: "🛏️", type: "Sleeping bag -5°C", name: "Naturehike UL", price: "₹3,499", link: "Amazon", rot: -0.5 },
  { ic: "🔋", type: "Power bank 20K", name: "Mi 20000mAh", price: "₹1,499", link: "Amazon", rot: 0.9 },
] as const;

export const FOOTER_LINKS = {
  pilgrimages: [
    { label: "Kedarnath", href: "/kedarnath" },
    { label: "Vaishno Devi", href: "/vaishno-devi" },
    { label: "Badrinath", href: "#" },
    { label: "Gangotri", href: "#" },
    { label: "Yamunotri", href: "#" },
    { label: "Tirupati", href: "#" },
    { label: "Kashi Vishwanath", href: "#" },
  ],
  adventures: [
    { label: "Spiti Valley", href: "/spiti" },
    { label: "Leh–Ladakh", href: "#" },
    { label: "Chopta–Tungnath", href: "#" },
    { label: "Valley of Flowers", href: "#" },
    { label: "Hampta Pass", href: "#" },
    { label: "Rishikesh", href: "#" },
  ],
  tools: [
    { label: "Live road status", href: "/road-status" },
    { label: "Packing checklist", href: "/kedarnath/packing" },
    { label: "Preparedness score", href: "#" },
    { label: "Budget calculator", href: "#" },
    { label: "Gear recommendations", href: "#" },
    { label: "Emergency contacts", href: "#" },
  ],
} as const;
