export const DESTINATIONS = [
  { name: "Kedarnath", slug: "kedarnath", info: "3,583m · Uttarakhand", note: "16 km trek to the Jyotirlinga", temp: "4°⛅", image: "/kedarnath.jpg", grad: "linear-gradient(150deg,#2d1b60,#5a3d7a 60%,#8a6a4a)", rot: -2, color: "#7c3aed", type: "pilgrimage" as const, activities: ["trekking", "pilgrimage"] as string[],
    wx: { icon: "⛅", temp: 4, feels: 1, hum: 55, wind: 22, aqi: 32, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Partly cloudy", alt: "3,583m", sunrise: "5:42 AM", sunset: "6:58 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 8, lo: 0 },{ day: "Thursday", icon: "⛅", hi: 6, lo: -2 },{ day: "Friday", icon: "🌧️", hi: 4, lo: -3 }] },
    routes: [
      { route: "Rishikesh → Rudraprayag", status: "open" as const, note: "NH-7, clear" },
      { route: "Rudraprayag → Guptkashi", status: "open" as const, note: "Narrow road" },
      { route: "Guptkashi → Sonprayag", status: "open" as const, note: "Clear" },
      { route: "Gaurikund → Kedarnath", status: "open" as const, note: "Trek, maintained" },
    ],
    packItems: ["Thermals ×2", "Trekking shoes", "Rain poncho", "Fleece jacket", "Power bank", "First aid kit", "Cash ₹10K+", "Char Dham e-pass"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Rudraprayag Police", number: "01364-233512" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "16 km" }, { icon: "⏱️", label: "Duration", value: "4–6 days" }, { icon: "💰", label: "Budget", value: "₹5K–35K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Spiti Valley", slug: "spiti", info: "3,650m · Himachal", note: "cold desert, ancient monasteries", temp: "10°☀️", image: "/spiti.jpg", grad: "linear-gradient(150deg,#3a3020,#5a5030 60%,#3a5040)", rot: 1.5, color: "#b45309", type: "adventure" as const, activities: ["road-trip", "biking", "camping"] as string[],
    wx: { icon: "☀️", temp: 10, feels: 7, hum: 25, wind: 8, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Clear sky", alt: "3,650m", sunrise: "5:38 AM", sunset: "7:12 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 18, lo: 2 },{ day: "Thursday", icon: "☀️", hi: 17, lo: 1 },{ day: "Friday", icon: "⛅", hi: 14, lo: 0 }] },
    routes: [
      { route: "Manali → Rohtang", status: "open" as const, note: "Clear" },
      { route: "Rohtang → Batal", status: "partial" as const, note: "BRO repair" },
      { route: "Batal → Kunzum → Kaza", status: "open" as const, note: "Gravel descent" },
      { route: "Sumdo → Reckong Peo", status: "partial" as const, note: "Rockfall zone" },
    ],
    packItems: ["Down jacket", "Thermals ×2", "Jerry can (fuel)", "Cash ₹15K+", "Power bank ×2", "Sleeping bag", "Sunglasses UV400", "ILP + Rohtang permit"],
    emergency: [{ name: "Kaza PHC", number: "01906-222340" }, { name: "BRO Helpline", number: "1800-180-6763" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛣️", label: "Circuit", value: "~630 km" }, { icon: "⏱️", label: "Duration", value: "8–12 days" }, { icon: "⛽", label: "Fuel warning", value: "No pump Batal–Kaza" }, { icon: "🏧", label: "ATM warning", value: "Unreliable in Kaza" }],
  },
  { name: "Vaishno Devi", slug: "vaishno-devi", info: "1,584m · J&K", note: "India's most visited shrine", temp: "18°🌤️", image: "/vaishno-devi.jpg", grad: "linear-gradient(150deg,#5a1a1a,#7a3030 60%,#5a2020)", rot: -1, color: "#be123c", type: "pilgrimage" as const, activities: ["trekking", "pilgrimage"] as string[],
    wx: { icon: "🌤️", temp: 18, feels: 17, hum: 65, wind: 8, aqi: 45, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "1,584m", sunrise: "5:35 AM", sunset: "7:20 PM",
      forecast: [{ day: "Tomorrow", icon: "🌤️", hi: 24, lo: 14 },{ day: "Thursday", icon: "☀️", hi: 26, lo: 15 },{ day: "Friday", icon: "⛅", hi: 22, lo: 13 }] },
    routes: [
      { route: "Jammu → Katra", status: "open" as const, note: "NH-44, good" },
      { route: "Katra → Bhawan", status: "open" as const, note: "Trek, normal crowd" },
    ],
    packItems: ["Comfortable shoes", "Light jacket", "Rain poncho", "Water bottle", "Power bank", "Cash ₹3K+", "Aadhaar original", "Yatra slip printed"],
    emergency: [{ name: "Shrine Board", number: "1800-180-1988" }, { name: "Katra Police", number: "01991-232500" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "13 km" }, { icon: "⏱️", label: "Duration", value: "2–3 days" }, { icon: "💰", label: "Budget", value: "₹3K–15K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Ladakh", slug: "ladakh", info: "3,524m · Ladakh", note: "Khardung La, Pangong, the ride", temp: "12°☀️", image: "/ladakh.jpg", grad: "linear-gradient(150deg,#1a2a4a,#2a5a7a 60%,#3a3a2a)", rot: 2, color: "#0369a1", type: "adventure" as const, activities: ["road-trip", "biking", "camping"] as string[],
    wx: { icon: "☀️", temp: 12, feels: 9, hum: 20, wind: 10, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Clear sky", alt: "3,524m", sunrise: "5:25 AM", sunset: "7:35 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 20, lo: 3 },{ day: "Thursday", icon: "☀️", hi: 19, lo: 2 },{ day: "Friday", icon: "⛅", hi: 16, lo: 1 }] },
    routes: [
      { route: "Manali → Rohtang", status: "open" as const, note: "Clear" },
      { route: "Rohtang → Baralacha", status: "partial" as const, note: "Patches near Darcha" },
      { route: "Baralacha → Pang", status: "open" as const, note: "Clear" },
      { route: "Pang → Leh", status: "open" as const, note: "Via Tanglang La" },
    ],
    packItems: ["Down jacket", "Thermals ×3", "Riding gloves", "Cash ₹20K+", "Power bank ×2", "Sunscreen SPF50", "Diamox", "Vehicle docs + permit"],
    emergency: [{ name: "Leh Hospital", number: "01982-252014" }, { name: "BRO Helpline", number: "1800-180-6763" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛣️", label: "Manali–Leh", value: "479 km" }, { icon: "⏱️", label: "Duration", value: "10–15 days" }, { icon: "🏔️", label: "Highest pass", value: "Khardung La 5,359m" }, { icon: "⛽", label: "Last fuel", value: "Tandi / Upshi" }],
  },
  { name: "Chopta", slug: "chopta", info: "3,680m · Uttarakhand", note: "gentle trek to highest Shiva temple", temp: "6°⛅", image: "/chopta.jpg", grad: "linear-gradient(150deg,#1a3a2a,#3a6a4a 60%,#2a5a1a)", rot: -0.5, color: "#15803d", type: "adventure" as const, activities: ["trekking", "nature", "camping"] as string[],
    wx: { icon: "⛅", temp: 6, feels: 3, hum: 50, wind: 15, aqi: 35, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Misty", alt: "3,680m", sunrise: "5:40 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "⛅", hi: 12, lo: 1 },{ day: "Thursday", icon: "🌧️", hi: 8, lo: -1 },{ day: "Friday", icon: "⛅", hi: 10, lo: 0 }] },
    routes: [
      { route: "Rishikesh → Ukhimath", status: "open" as const, note: "Via Rudraprayag" },
      { route: "Ukhimath → Chopta", status: "open" as const, note: "Scenic road" },
      { route: "Chopta → Tungnath", status: "open" as const, note: "3.5 km trek" },
    ],
    packItems: ["Fleece jacket", "Trekking shoes", "Rain poncho", "Water bottle", "Power bank", "Cash ₹5K+", "Sunscreen", "First aid kit"],
    emergency: [{ name: "SDRF Uttarakhand", number: "1070" }, { name: "Ukhimath PHC", number: "01364-240235" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🥾", label: "Trek distance", value: "3.5 km" }, { icon: "⏱️", label: "Duration", value: "3–4 days" }, { icon: "💰", label: "Budget", value: "₹4K–12K" }, { icon: "🏔️", label: "Tungnath alt.", value: "3,680m" }],
  },
  { name: "Badrinath", slug: "badrinath", info: "3,133m · Uttarakhand", note: "easiest Char Dham, drive-to temple", temp: "10°⛅", image: "/badrinath.jpg", grad: "linear-gradient(150deg,#2d1060,#4a2080 60%,#6a3060)", rot: 1, color: "#6d28d9", type: "pilgrimage" as const, activities: ["pilgrimage", "road-trip"] as string[],
    wx: { icon: "⛅", temp: 10, feels: 7, hum: 45, wind: 15, aqi: 28, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Partly cloudy", alt: "3,133m", sunrise: "5:38 AM", sunset: "7:02 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 14, lo: 3 },{ day: "Thursday", icon: "⛅", hi: 12, lo: 2 },{ day: "Friday", icon: "🌧️", hi: 9, lo: 1 }] },
    routes: [
      { route: "Rishikesh → Joshimath", status: "open" as const, note: "NH-7, 250 km" },
      { route: "Joshimath → Badrinath", status: "open" as const, note: "45 km" },
      { route: "Badrinath → Mana Village", status: "open" as const, note: "3 km walk" },
    ],
    packItems: ["Warm jacket", "Thermals", "Walking shoes", "Towel for Tapt Kund", "Cash ₹5K+", "E-pass printed", "Power bank", "First aid kit"],
    emergency: [{ name: "Badrinath PHC", number: "01381-222226" }, { name: "SDRF Uttarakhand", number: "1070" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🛕", label: "Temple type", value: "Char Dham" }, { icon: "🚗", label: "From Rishikesh", value: "295 km" }, { icon: "💰", label: "Budget", value: "₹3K–20K" }, { icon: "📋", label: "Registration", value: "Mandatory" }],
  },
  { name: "Rishikesh", slug: "rishikesh", info: "372m · Uttarakhand", note: "gateway to the Himalayas", temp: "28°☀️", image: "/rishikesh.jpg", grad: "linear-gradient(150deg,#064e3b,#059669 60%,#0d9488)", rot: -1.5, color: "#059669", type: "adventure" as const, activities: ["rafting", "camping", "yoga"] as string[],
    wx: { icon: "☀️", temp: 28, feels: 30, hum: 60, wind: 8, aqi: 55, aqiLabel: "Moderate", aqiColor: "#f59e0b", cond: "Sunny", alt: "372m", sunrise: "5:35 AM", sunset: "7:05 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 32, lo: 22 },{ day: "Thursday", icon: "⛅", hi: 30, lo: 21 },{ day: "Friday", icon: "☀️", hi: 33, lo: 23 }] },
    routes: [
      { route: "Dehradun → Rishikesh", status: "open" as const, note: "43 km, 1 hr" },
      { route: "Delhi → Rishikesh", status: "open" as const, note: "240 km, 5–6 hrs" },
      { route: "Rishikesh → Rudraprayag", status: "open" as const, note: "NH-7, 140 km" },
    ],
    packItems: ["Cash (full trip budget)", "E-pass printed", "Trekking shoes", "Rain gear", "Power bank", "Offline maps", "Diamox", "First aid kit"],
    emergency: [{ name: "AIIMS Rishikesh", number: "0135-2462930" }, { name: "Rishikesh Police", number: "0135-2430245" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏧", label: "ATMs", value: "20+ reliable" }, { icon: "🚣", label: "Rafting", value: "₹800–1,500" }, { icon: "🧘", label: "Yoga", value: "Ashrams available" }, { icon: "🛣️", label: "To Kedarnath", value: "248 km" }],
  },
  { name: "Valley of Flowers", slug: "valley-of-flowers", info: "3,658m · Uttarakhand", note: "UNESCO trek, 500+ wildflower species", temp: "10°🌧️", image: "/valley-of-flowers.jpg", grad: "linear-gradient(150deg,#4a1060,#86198f 60%,#c026d3)", rot: 0.5, color: "#86198f", type: "adventure" as const, activities: ["trekking", "nature"] as string[],
    wx: { icon: "🌧️", temp: 10, feels: 7, hum: 85, wind: 10, aqi: 22, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Monsoon bloom", alt: "3,658m", sunrise: "5:40 AM", sunset: "7:00 PM",
      forecast: [{ day: "Tomorrow", icon: "🌧️", hi: 12, lo: 5 },{ day: "Thursday", icon: "⛅", hi: 14, lo: 4 },{ day: "Friday", icon: "🌧️", hi: 10, lo: 3 }] },
    routes: [
      { route: "Rishikesh → Govindghat", status: "open" as const, note: "270 km, 9–10 hrs" },
      { route: "Govindghat → Ghangaria", status: "open" as const, note: "14 km trek" },
      { route: "Ghangaria → Valley", status: "open" as const, note: "3 km trail" },
    ],
    packItems: ["Waterproof shoes", "Rain jacket", "Leech socks", "Warm fleece", "Cash ₹5K–8K", "Camera", "Power bank", "Diamox"],
    emergency: [{ name: "Joshimath Hospital", number: "01389-222215" }, { name: "SDRF Uttarakhand", number: "1070" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🌸", label: "Species", value: "500+" }, { icon: "📅", label: "Best month", value: "August" }, { icon: "🎫", label: "Entry fee", value: "₹750" }, { icon: "🥾", label: "Trek", value: "17 km" }],
  },
  { name: "Manali", slug: "manali", info: "2,050m · Himachal Pradesh", note: "gateway to Ladakh and Spiti", temp: "18°🌤️", image: "/manali.jpg", grad: "linear-gradient(150deg,#1a3a5a,#2a6a4a 60%,#3a4a2a)", rot: -0.5, color: "#2563eb", type: "adventure" as const, activities: ["road-trip", "rafting", "biking", "camping"] as string[],
    wx: { icon: "🌤️", temp: 18, feels: 16, hum: 50, wind: 10, aqi: 30, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "2,050m", sunrise: "5:40 AM", sunset: "7:10 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 22, lo: 8 },{ day: "Thursday", icon: "⛅", hi: 20, lo: 7 },{ day: "Friday", icon: "🌧️", hi: 16, lo: 6 }] },
    routes: [
      { route: "Dehradun → Manali", status: "open" as const, note: "530 km, 10-12 hrs" },
      { route: "Manali → Leh", status: "open" as const, note: "479 km (Jun-Oct)" },
      { route: "Manali → Rohtang", status: "open" as const, note: "51 km" },
    ],
    packItems: ["Warm jacket", "Rain gear", "Fuel cans (if biking north)", "Cash ₹15K+", "Power bank", "Offline maps", "First aid kit"],
    emergency: [{ name: "Manali Hospital", number: "01902-252375" }, { name: "Manali Police", number: "01902-252126" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🏍️", label: "To Leh", value: "479 km" }, { icon: "🎿", label: "Solang Valley", value: "14 km" }, { icon: "💰", label: "Budget", value: "₹3K-15K" }, { icon: "📅", label: "Best month", value: "September" }],
  },
  { name: "Shimla", slug: "shimla", info: "2,206m · Himachal Pradesh", note: "colonial hill station, Spiti gateway", temp: "15°🌤️", image: "/shimla.jpg", grad: "linear-gradient(150deg,#4a2020,#8a4040 60%,#6a3030)", rot: 1, color: "#dc2626", type: "adventure" as const, activities: ["road-trip", "nature"] as string[],
    wx: { icon: "🌤️", temp: 15, feels: 13, hum: 55, wind: 12, aqi: 40, aqiLabel: "Good", aqiColor: "#22c55e", cond: "Pleasant", alt: "2,206m", sunrise: "5:38 AM", sunset: "7:08 PM",
      forecast: [{ day: "Tomorrow", icon: "☀️", hi: 20, lo: 8 },{ day: "Thursday", icon: "⛅", hi: 18, lo: 7 },{ day: "Friday", icon: "🌧️", hi: 14, lo: 6 }] },
    routes: [
      { route: "Dehradun → Shimla", status: "open" as const, note: "245 km, 5.5 hrs" },
      { route: "Shimla → Reckong Peo", status: "open" as const, note: "220 km, NH-5" },
      { route: "Shimla → Kaza (Spiti)", status: "open" as const, note: "415 km, 2 days" },
    ],
    packItems: ["Warm jacket", "Rain gear", "Cash ₹20K+ for Spiti", "Fuel for onward", "Offline maps", "Diamox", "Dry snacks"],
    emergency: [{ name: "IGMC Hospital", number: "0177-2804251" }, { name: "Shimla Police", number: "0177-2812344" }, { name: "Disaster Helpline", number: "112" }],
    quickFacts: [{ icon: "🚂", label: "Toy train", value: "Kalka-Shimla" }, { icon: "🛣️", label: "To Kaza", value: "415 km" }, { icon: "💰", label: "Budget", value: "₹2.5K-12K" }, { icon: "📅", label: "Best months", value: "Sep-Oct" }],
  },
];

export const SEARCH_DESTINATIONS = [
  ...DESTINATIONS.map(d => ({ name: d.name, slug: d.slug, info: d.info, color: d.color, type: d.type, activities: d.activities })),
];

export const ACTIVITIES = [
  { key: "trekking", label: "Trekking", icon: "🥾" },
  { key: "pilgrimage", label: "Pilgrimage", icon: "🙏" },
  { key: "road-trip", label: "Road trip", icon: "🛣️" },
  { key: "camping", label: "Camping", icon: "⛺" },
  { key: "nature", label: "Nature & wildlife", icon: "🌿" },
  { key: "rafting", label: "Rafting", icon: "🚣" },
  { key: "biking", label: "Biking", icon: "🏍️" },
  { key: "yoga", label: "Yoga & wellness", icon: "🧘" },
] as const;

export const GUIDES = [
  { slug: "acclimatize-above-3000m", title: "How to acclimatize above 3,000m - AMS, Diamox and ascent rules", tag: "Health", min: 14, rot: -1.5, href: "/guides/acclimatize-above-3000m", desc: "Practical acclimatization guide for treks above 3,000m in India. Altitude sickness symptoms, Diamox dosage and timing, safe ascent rates, hydration, and when to descend. Written from Dehradun." },
  { slug: "best-time-char-dham", title: "Best time to visit Char Dham - Kedarnath, Badrinath, Gangotri, Yamunotri", tag: "Planning", min: 16, rot: 1, href: "/guides/best-time-char-dham", desc: "Temple opening dates, month-by-month conditions, crowd windows, helicopter availability, and the honest case for September-October over May. Written from Dehradun." },
  { slug: "packing-4000m", title: "What to pack for 4,000m+ altitude treks in India", tag: "Packing", min: 18, rot: -0.5, href: "/guides/packing-4000m", desc: "The 3-layer clothing system, summer vs late-season gear lists, weight targets under 8 kg, and where to buy everything in Dehradun. Written from experience." },
  { slug: "monsoon-routes", title: "Monsoon travel: which mountain routes to avoid", tag: "Safety", min: 4, rot: -1, href: "/guides/monsoon-routes", desc: "Landslide-prone zones, BRO repair schedules, and safe alternatives during July–September." },
  { slug: "atm-cash-guide", title: "ATM and cash guide for remote Himalayan towns", tag: "Money", min: 20, rot: 0.8, href: "/guides/atm-cash-guide", desc: "Town-by-town ATM reliability, UPI dead zones, network coverage, and cash carry recommendations for Char Dham, Spiti, Ladakh and Vaishno Devi routes. Written from Dehradun." },
  { slug: "char-dham-epass", title: "Char Dham e-pass and permits - how to register online (2026)", tag: "Documents", min: 22, rot: -0.8, href: "/guides/char-dham-epass", desc: "Step-by-step Char Dham registration, daily pilgrim caps, Spiti ILP, Rohtang permit, and Ladakh PAP. Common rejection reasons and what to do. Written from Dehradun." },
  { slug: "kedarnath-budget", title: "Kedarnath trip under Rs 8,000 - a day-by-day budget breakdown", tag: "Budget", min: 18, rot: 1.2, href: "/guides/kedarnath-budget", desc: "Complete day-by-day cost split from Rishikesh to Kedarnath and back. Transport, food, accommodation, and helicopter comparison. 2026 season prices." },
] as const;

export const GEAR = [
  { ic: "🥾", type: "Trekking shoes", name: "Quechua MH500", price: "₹3,999", link: "Amazon", rot: -0.8 },
  { ic: "🧥", type: "Windproof jacket", name: "Forclaz MT500", price: "₹4,999", link: "Decathlon", rot: 1.2 },
  { ic: "🛏️", type: "Sleeping bag -5°C", name: "Naturehike UL", price: "₹3,499", link: "Amazon", rot: -0.5 },
  { ic: "🔋", type: "Power bank 20K", name: "Mi 20000mAh", price: "₹1,499", link: "Amazon", rot: 0.9 },
] as const;

export const FOOTER_LINKS = {
  pilgrimages: [
    { label: "Kedarnath", href: "/kedarnath" },
    { label: "Vaishno Devi", href: "/vaishno-devi" },
    { label: "Badrinath", href: "#" },
    { label: "Gangotri", href: "#" },
    { label: "Yamunotri", href: "#" },
    { label: "Tirupati", href: "#" },
    { label: "Kashi Vishwanath", href: "#" },
  ],
  adventures: [
    { label: "Spiti Valley", href: "/spiti" },
    { label: "Leh–Ladakh", href: "#" },
    { label: "Chopta–Tungnath", href: "#" },
    { label: "Valley of Flowers", href: "#" },
    { label: "Hampta Pass", href: "#" },
    { label: "Rishikesh", href: "#" },
  ],
  tools: [
    { label: "Live road status", href: "/road-status" },
    { label: "Packing checklist", href: "/kedarnath/packing" },
    { label: "Preparedness score", href: "#" },
    { label: "Budget calculator", href: "#" },
    { label: "Gear recommendations", href: "#" },
    { label: "Emergency contacts", href: "#" },
  ],
} as const;
