import type { DestinationData } from "./types";

export const badrinath: DestinationData = {
  slug: "badrinath",
  name: "Badrinath",
  tagline: "The most accessible Char Dham - drive to the temple at 3,133m",
  region: "Garhwal",
  state: "Uttarakhand",
  type: "pilgrimage",
  altitude: 3133,
  temp: 10,
  weather: "Clear",
  season: "May-June, September-October",
  duration: "2-3 days",
  budget: { min: 3000, max: 20000 },
  heroGradient: "linear-gradient(150deg,#2d1060,#4a2080 60%,#6a3060)",
  metaTitle: "Badrinath Temple Guide 2026 - Route, Darshan, Mana Village, Budget | TravelBoa",
  metaDescription: "Complete Badrinath guide. NH-7 route from Rishikesh via Joshimath, temple darshan timings, Tapt Kund, Mana village day trip, GMVN accommodation, helicopter option, and budget breakdown.",
  quickStats: [
    { label: "Altitude", value: "3,133m", icon: "🏔️" },
    { label: "From Rishikesh", value: "295 km", icon: "🚗" },
    { label: "Trek required", value: "None", icon: "🚶" },
    { label: "Best time", value: "Sep-Oct", icon: "📅" },
    { label: "Duration", value: "2-3 days", icon: "⏱️" },
    { label: "Budget", value: "Rs 3K-20K", icon: "💰" },
  ],
  intro: "Badrinath is the easiest of the four Char Dham temples to reach. There is no trek. You drive to 3,133m, park the car, walk 200 metres, and you are at the temple. That accessibility makes it the most visited of the four - and also means the logistics are different from Kedarnath in every way.\n\nThe route from Rishikesh covers 295 km on NH-7 and then the Badrinath National Highway through Joshimath. The road is paved the entire way. I have done Badrinath twice - once as a quick overnight from Rishikesh and once with the full Mana village day-trip. The two-night version is the right call.",
  sections: [
    { id: "route", title: "The route: Rishikesh to Badrinath", icon: "🛣️",
      content: "295 km on NH-7 via Devprayag, Rudraprayag, Karnaprayag, Nandprayag, Chamoli, Pipalkoti, and Joshimath. Road is paved throughout. Drive time: 9-10 hours with stops.\n\nJoshimath (1,890m) is the last major town before Badrinath, 45 km out. Fuel, ATMs (SBI), restaurants, and accommodation all available here. If arriving late, sleep in Joshimath rather than pushing to Badrinath in the dark - the last 45 km is narrow mountain road.\n\nTransport options: GMOU/UPSRTC bus from Rishikesh ISBT (Rs 500-700), shared Sumo from Rishikesh (Rs 800-1,200), private taxi (Rs 5,000-8,000). Bus takes 10-12 hours.\n\nThe Badrinath road shares the corridor with Kedarnath until Rudraprayag, then continues north toward Joshimath while the Kedarnath road turns east. Plan accordingly if doing both on the same trip." },
    { id: "darshan", title: "Temple darshan: timings and what to expect", icon: "🛕",
      content: "Badrinath temple opens for darshan twice daily:\n\nMorning: 4:30 AM (Maha Abhishek) to 1:00 PM\nEvening: 4:00 PM to 9:00 PM\n\nThe Maha Abhishek at 4:30 AM is the main ritual. Arrive by 4:00 AM for a good position. The temple closes for afternoon rest between 1:00 PM and 4:00 PM.\n\nQueue time in May peak: 2-4 hours. Queue time in September-October: 30 minutes to 1 hour. The difference is dramatic.\n\nDress code: no specific strict code but conservative clothing is expected. Remove shoes before entering. Photography is not allowed inside the sanctum.\n\nThe temple itself is compact. The black stone Vishnu idol (Badrinarayan) is the central deity. The entire darshan - queue to exit - takes 15-30 minutes once you reach the sanctum." },
    { id: "tapt-kund", title: "Tapt Kund: the hot spring", icon: "♨️",
      content: "Tapt Kund is a natural hot sulphur spring at the base of the temple. Water temperature: 45-55C. Tradition says pilgrims bathe here before darshan. Separate bathing areas for men and women.\n\nThe water is genuinely hot. In October, stepping from 2C morning air into 50C water and then back out is a shock. Brief immersion (2-5 minutes) is the norm. There is also a cold pool (Narad Kund) nearby for contrast.\n\nPractical note: bring a change of dry clothes and a towel. The changing facilities are basic." },
    { id: "mana", title: "Mana village: the better reason for a second night", icon: "🏘️",
      content: "Mana village is 3 km from Badrinath temple and is officially the last Indian village before the Tibetan border. It is the reason to stay two nights instead of one.\n\nWalk from Badrinath to Mana (3 km, 30-40 minutes). The village is home to the Bhotiya community. Key sites: Vyas Gufa (cave where Vyasa is said to have composed the Mahabharata), Bhim Pul (natural rock bridge over the Saraswati river), and the Saraswati river origin point where it emerges from underground.\n\nThe last Indian dhaba (literally - there is a sign) serves chai, Maggi, and parathas with a view of the border mountains. Worth the walk for that alone.\n\nMana is best in the morning. Leave Badrinath by 7 AM, reach Mana by 7:30, explore for 2-3 hours, return for afternoon darshan or departure." },
    { id: "accommodation", title: "Accommodation", icon: "🏨",
      content: "GMVN Devlok (Badrinath): Government guesthouse right near the temple. Rs 800-2,500 per room. Clean, functional, well-located. Book at gmvnl.in.\n\nPrivate hotels: Rs 1,000-3,000 per room in season. Quality varies significantly. Hotels near the bus stand are cheaper but noisier.\n\nJoshimath (45 km away): Better value accommodation with more options. Rs 600-1,500 per room. Useful if arriving late or if Badrinath hotels are full.\n\nPeak season (May-June weekends): Book GMVN 2 weeks ahead. September-October: walk-in availability most days." },
    { id: "helicopter", title: "Helicopter option from Dehradun", icon: "🚁",
      content: "Helicopter service operates from Dehradun (Sahastradhara helipad) to Badrinath directly. One-way ticket: Rs 6,000-8,000. Flight time: approximately 45 minutes.\n\nBook through IRCTC HeliYatra portal or authorized operators. Availability is better than Kedarnath helicopter slots because demand is lower.\n\nThe helicopter eliminates the 295 km road journey entirely. For pilgrims with limited time or mobility issues, this is a genuine option. Return helicopter + 1 night stay makes Badrinath possible as a 2-day trip from Dehradun." },
    { id: "budget", title: "Budget breakdown", icon: "💰",
      content: "Budget (Rs 3,000-5,000): Bus from Rishikesh Rs 500-700, GMVN dormitory Rs 400-600/night x2, dhaba meals Rs 150-250/day, total Rs 3,000-5,000.\n\nMid-range (Rs 8,000-12,000): Shared Sumo Rs 800-1,200, private hotel Rs 1,500-2,500/night x2, restaurant meals Rs 300-500/day.\n\nComfort (Rs 15,000-20,000): Private taxi Rs 5,000-8,000, good hotel Rs 2,500-3,500/night x2, meals at hotel.\n\nHelicopter (Rs 20,000-30,000): Helicopter both ways Rs 12,000-16,000, hotel Rs 2,500/night, meals Rs 500/day.\n\nCash note: Joshimath ATMs work. Badrinath has 1-2 ATMs that are semi-reliable. Carry Rs 5,000+ cash from Joshimath." },
    { id: "best-time", title: "Best time to visit", icon: "📅",
      content: "May-June: Peak season. Temple freshly opened. Crowds high, especially weekends. Weather: 8-18C days, 2-5C nights. Helicopter and accommodation book up.\n\nJuly-August: Monsoon. Temple open but road risk from landslides. Avoid unless experienced.\n\nSeptember-October: The recommended window. Crowds drop dramatically. Clear views of Neelkanth peak behind the temple. Weather: 5-15C days, 0-5C nights. Book GMVN 1 week ahead.\n\nNovember: Closing ceremony around Bhai Dooj. Temple closes for winter. Very cold.\n\nSee /guides/best-time-char-dham for the full month-by-month analysis." },
    { id: "valley-of-flowers", title: "Combining with Valley of Flowers", icon: "🌸",
      content: "Valley of Flowers National Park is accessible from Govindghat, which is 25 km before Badrinath on the same road. The park opens July to September (peak bloom: August).\n\nCombination itinerary: Joshimath base, Day 1 drive to Govindghat and trek to Ghangaria (14 km). Day 2 Valley of Flowers (round trip from Ghangaria). Day 3 optional Hemkund Sahib. Day 4 return to Joshimath, drive to Badrinath. Day 5 Badrinath darshan + Mana village.\n\nThis combination works best in August-September when both Valley of Flowers is in bloom and Badrinath is open with lower crowds." },
  ],
  weatherPoints: [
    { location: "Badrinath", altitude: 3133, temp: 10, weather: "☀️" },
    { location: "Joshimath", altitude: 1890, temp: 18, weather: "🌤️" },
    { location: "Mana Village", altitude: 3200, temp: 8, weather: "💨" },
  ],
  routes: [
    { from: "Rishikesh", to: "Badrinath", status: "open", note: "295 km, NH-7" },
    { from: "Joshimath", to: "Badrinath", status: "open", note: "45 km" },
    { from: "Badrinath", to: "Mana Village", status: "open", note: "3 km walk" },
  ],
  checklist: [
    { category: "Documents", items: [
      { name: "Char Dham e-pass (printed)", essential: true },
      { name: "Aadhaar / ID proof x2", essential: true },
      { name: "Vehicle RC if driving", essential: false },
    ] },
    { category: "Clothing", items: [
      { name: "Warm jacket (down or fleece)", essential: true },
      { name: "Thermal base layer", essential: true },
      { name: "Walking shoes (not sandals)", essential: true },
      { name: "Change of clothes for Tapt Kund", essential: true },
      { name: "Towel", essential: true },
    ] },
    { category: "Essentials", items: [
      { name: "Cash Rs 5,000+", essential: true },
      { name: "Power bank", essential: true },
      { name: "Sunscreen SPF50", essential: true },
      { name: "First aid kit", essential: false },
      { name: "Water bottle", essential: true },
    ] },
  ],
  faq: [
    { q: "Is there a trek to Badrinath temple?", a: "No. You drive to the town and walk 200 metres to the temple. No trekking required. This makes Badrinath accessible for elderly pilgrims and families with children." },
    { q: "Is Mana village worth visiting?", a: "Yes, strongly recommended. The Vyas Gufa, Bhim Pul, and the last Indian dhaba make it worth a 2-3 hour morning trip. It is the reason to stay two nights." },
    { q: "Can I do Badrinath and Kedarnath on the same trip?", a: "Yes. The standard approach is Kedarnath first (via Rudraprayag-Guptkashi), then Badrinath (via Rudraprayag-Joshimath). Add 3-4 days to your Kedarnath itinerary." },
    { q: "How cold is Badrinath in October?", a: "Days 5-15C, nights 0-5C. A down jacket, thermals, and warm shoes are needed. The temple interior is cold - carry a warm layer." },
    { q: "Is the helicopter worth it?", a: "For time-constrained pilgrims, yes. It reduces a 10-hour drive to 45 minutes. Rs 6,000-8,000 one way. Makes Badrinath possible as a 2-day trip from Dehradun." },
    { q: "Do I need the Char Dham e-pass for Badrinath?", a: "Yes. Mandatory registration at registrationandtouristcare.uk.gov.in. Same system as Kedarnath. See /guides/char-dham-epass for the step-by-step process." },
  ],
  emergency: [
    { name: "Badrinath PHC", number: "01381-222226" },
    { name: "Joshimath Police", number: "01389-222215" },
    { name: "SDRF Uttarakhand", number: "1070" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [
    { slug: "packing", title: "Badrinath packing checklist", description: "What to pack for a Badrinath pilgrimage" },
  ],
};
