import type { DestinationData } from "./types";

export const chopta: DestinationData = {
  slug: "chopta",
  name: "Chopta",
  tagline: "Weekend trek to the highest Shiva temple - 218 km from Dehradun",
  region: "Garhwal",
  state: "Uttarakhand",
  type: "adventure",
  altitude: 2680,
  temp: 6,
  weather: "Clear",
  season: "April-June, September-November",
  duration: "2-3 days",
  budget: { min: 3500, max: 5000 },
  heroGradient: "linear-gradient(150deg,#1a3a2a,#3a6a4a 60%,#2a5a1a)",
  metaTitle: "Chopta Tungnath Trek 2026: Weekend Trip from Dehradun | TravelBoa",
  metaDescription: "Chopta-Tungnath-Chandrashila trek guide. 3.5 km trail to the highest Shiva temple, route from Dehradun, budget ₹4K-12K, best season, and camping options.",
  quickStats: [
    { label: "Base altitude", value: "2,680m", icon: "🏔️" },
    { label: "Tungnath", value: "3,680m", icon: "🛕" },
    { label: "Chandrashila", value: "4,130m", icon: "⛰️" },
    { label: "From Dehradun", value: "218 km", icon: "🚗" },
    { label: "Trek distance", value: "5 km one way", icon: "🥾" },
    { label: "Budget", value: "Rs 3.5K-5K", icon: "💰" },
  ],
  intro: "I have done the Chopta-Tungnath trek four times. I recommended it to probably thirty people over the last two years. Not because it is easy - 3.5 km on a steep stone path with 580m of altitude gain is not casual - but because it is the closest thing to a real high-altitude trek that someone can do from Dehradun on a 3-day weekend without hiring a guide, booking a tour, or spending more than Rs 5,000 including transport.\n\n218 km from Dehradun. 5-6 hours by road. 3.5 km up to the Tungnath temple at 3,680m, the world's highest Shiva temple. Another 1.5 km if you push to Chandrashila summit at 4,130m. One night camping in the meadow if you time it right. Back home Sunday night.",
  sections: [
    { id: "drive", title: "The drive: Dehradun to Chopta", icon: "🚗",
      content: "218 km via Rishikesh, Devprayag, Srinagar (Uttarakhand), Rudraprayag, Ukhimath. 5-6 hours in good conditions. The road is paved throughout - NH-7 to Rudraprayag, then the Kedarnath/Chopta branch via Ukhimath.\n\nFuel up in Rishikesh or Rudraprayag. No reliable fuel between Rudraprayag and Chopta (78 km).\n\nThe last 18 km from Ukhimath to Chopta is a narrow hill road through dense oak and rhododendron forest. Single lane in places, with blind corners. Drive this section in daylight.\n\nParking at Chopta: a small clearing at the trailhead. Rs 50-100 per vehicle per day. Secure enough - locals watch the area." },
    { id: "trek", title: "The trek: Chopta to Tungnath to Chandrashila", icon: "🥾",
      content: "Chopta (2,680m) to Tungnath temple (3,680m): 3.5 km, stone-paved path, 580m elevation gain. Takes 2-3 hours up, 1.5-2 hours down. The path is well-marked and impossible to lose. One chai stall midway (seasonal).\n\nTungnath to Chandrashila summit (4,130m): 1.5 km further, 450m additional gain. Steeper, rockier, not paved. The last 300m is a scramble over loose rock. This section requires proper trekking shoes - not sports shoes, not sandals.\n\nChandrashila summit: 360-degree view of Nanda Devi, Trisul, Chaukhamba, Kedarnath, and Bandarpunch ranges. On a clear October morning, this is one of the best viewpoints in Uttarakhand.\n\nStart early: leave Chopta by 6-7 AM to reach Chandrashila before afternoon cloud builds." },
    { id: "camping", title: "Camping vs tent stay", icon: "⛺",
      content: "Tent stays at Chopta: Rs 500-800 per person including dinner and breakfast. Multiple operators at the trailhead meadow. Walk-in bookings work most of the season. October long weekends: call ahead.\n\nSelf-camping: permitted in the meadow area. Carry your own tent, sleeping bag rated to -5C for October, and food. No facilities beyond what the tent-stay operators provide.\n\nPractical advice: tent stays are the right call for first-timers. Self-camping is for experienced trekkers who own the gear. Renting camping equipment for Chopta specifically is not worth the cost." },
    { id: "october", title: "October: why it is the best month", icon: "🍂",
      content: "October at Chopta is the single best month. The monsoon has retreated. The air is clear. Snow sits on the high peaks but has not yet reached the trail. Temperatures are cold but manageable - 5-15C days, -2 to 5C nights at Chopta.\n\nFrom Chandrashila summit on a clear October morning, every major peak in the Garhwal Himalaya is visible. This view is obscured by cloud for 4 months during monsoon and often hazy in May-June.\n\nThe meadow at Chopta turns golden-brown in October. The rhododendron forest below glows in autumn light. This is not poetic exaggeration - it is genuinely one of the most photogenic locations in Uttarakhand in this window.\n\nAvoid: July-August (monsoon, trail is slippery and views are nil), December-February (snow covers the trail, Tungnath temple is closed)." },
    { id: "itinerary", title: "3-day itinerary from Dehradun", icon: "📋",
      content: "Day 1 (Friday evening or Saturday morning): Drive Dehradun to Chopta (218 km, 5-6 hours). If leaving Friday evening, stop at Rudraprayag for the night. If Saturday morning, leave by 5 AM to reach Chopta by noon.\n\nDay 2 (Saturday or Sunday): Trek Chopta to Tungnath to Chandrashila and back. 10 km round trip, 6-7 hours including time at the summit. Start by 6-7 AM.\n\nDay 3 (Sunday): Drive Chopta back to Dehradun. Leave by 7 AM to be home by 1-2 PM.\n\nAlternative: For a more relaxed trip, camp one night at Chopta and one night at Ukhimath or Guptkashi. This also works as an acclimatization base before a Kedarnath trek." },
    { id: "packing", title: "What to pack for Chopta", icon: "🎒",
      content: "Trekking shoes with ankle support (the Chandrashila scramble requires grip). Fleece or down jacket for early morning and camp. Waterproof shell if any rain is forecast. 1.5L water and snacks. Headlamp if starting early. Sunscreen and sunglasses.\n\nFor October camping add: sleeping bag rated to -5C comfort, thermal base layers, beanie and gloves, and a tent if self-camping.\n\nSee /guides/packing-4000m for the complete high-altitude packing list and /gear/trekking-shoes-under-5000 for shoe recommendations." },
    { id: "altitude", title: "Altitude and first-timer advice", icon: "💡",
      content: "Chopta at 2,680m is below the altitude where most people experience AMS. Tungnath at 3,680m is borderline. Chandrashila at 4,130m is altitude territory.\n\nIf this is your first time above 3,000m: drink water consistently on the trek, eat before you feel hungry, and do not push through headache or nausea on the Chandrashila section. The temple at Tungnath is the primary destination - Chandrashila is optional and weather-dependent.\n\nAcclimatization: if you drive from Dehradun (682m) to Chopta (2,680m) and trek to 4,130m in the same day, that is a 3,448m altitude gain. Go slowly. Rest at Tungnath before the Chandrashila push.\n\nSee /guides/acclimatize-above-3000m for the full protocol." },
  ],
  weatherPoints: [
    { location: "Chopta", altitude: 2680, temp: 10, weather: "☀️" },
    { location: "Tungnath", altitude: 3680, temp: 5, weather: "💨" },
    { location: "Chandrashila", altitude: 4130, temp: 2, weather: "❄️" },
  ],
  routes: [
    { from: "Dehradun", to: "Chopta", status: "open", note: "218 km, 5-6 hrs" },
    { from: "Rudraprayag", to: "Chopta via Ukhimath", status: "open", note: "78 km" },
    { from: "Chopta", to: "Tungnath", status: "open", note: "3.5 km trek" },
    { from: "Tungnath", to: "Chandrashila", status: "open", note: "1.5 km scramble" },
  ],
  checklist: [
    { category: "Clothing", items: [
      { name: "Trekking shoes with ankle support", essential: true },
      { name: "Fleece or down jacket", essential: true },
      { name: "Waterproof shell", essential: true },
      { name: "Quick-dry trousers", essential: true },
      { name: "Thermal base layer (October)", essential: true },
      { name: "Beanie and gloves (October)", essential: true },
    ] },
    { category: "Trail essentials", items: [
      { name: "Water 1.5L", essential: true },
      { name: "Snacks / energy bars", essential: true },
      { name: "Headlamp", essential: true },
      { name: "Sunscreen SPF50", essential: true },
      { name: "Sunglasses UV400", essential: true },
      { name: "Power bank", essential: false },
    ] },
    { category: "Camping (if self)", items: [
      { name: "Tent", essential: true },
      { name: "Sleeping bag -5C comfort", essential: true },
      { name: "Sleeping mat", essential: false },
      { name: "Stove and fuel", essential: false },
    ] },
  ],
  faq: [
    { q: "Is Chopta-Tungnath suitable for beginners?", a: "Yes, with caveats. The 3.5 km trail to Tungnath is manageable for anyone with reasonable fitness - the path is stone-paved and well-marked. The Chandrashila extension requires better fitness and proper footwear." },
    { q: "Is there any permit required?", a: "No forest permit or government registration. A small entry fee of Rs 20-50 is collected by the Tungnath temple trust at the trailhead." },
    { q: "Can I do it as a day trip from Dehradun?", a: "Technically yes, but the 5-6 hour drive each way plus 6-7 hours of trekking makes it a 17-18 hour day. Two-night trips give you time to acclimatize and enjoy the sunrise." },
    { q: "What is the best month?", a: "October. Clear skies, snow on peaks but not on trail, 360-degree visibility from Chandrashila summit." },
    { q: "What do tent camps include?", a: "Most include sleeping tent, blankets, dinner, and breakfast for Rs 500-800 per head. Walk-in bookings work for most of the season." },
    { q: "Is Chandrashila safe for kids?", a: "Tungnath is fine for kids above 8-10 years with supervision. Chandrashila scramble is not recommended for young children due to loose rock on the final section." },
  ],
  emergency: [
    { name: "Ukhimath PHC", number: "01364-274212" },
    { name: "SDRF Uttarakhand", number: "1070" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [
    { slug: "packing", title: "Chopta packing checklist", description: "Complete packing list for the Chopta-Tungnath-Chandrashila trek" },
  ],
};
