import type { DestinationData } from "./types";

export const dharamshala: DestinationData = {
  slug: "dharamshala",
  name: "Dharamshala & McLeodganj",
  tagline: "Triund trek, the Dalai Lama's monastery, and a Tibetan town in Himachal",
  region: "Kangra",
  state: "Himachal Pradesh",
  type: "adventure",
  altitude: 1457,
  temp: 18,
  weather: "Pleasant",
  season: "Mar-Jun, Sep-Nov",
  duration: "3-5 days",
  budget: { min: 2000, max: 12000 },
  heroGradient: "linear-gradient(150deg,#1f3a2d,#3a6a4a 60%,#5a8a6a)",
  metaTitle: "Dharamshala & McLeodganj 2026: Triund Trek, Tibetan Quarter Guide | TravelBoa",
  metaDescription: "Dharamshala and McLeodganj travel guide. Triund overnight trek, Dalai Lama temple, Tibetan quarter food walk, Indrahar Pass, Kangra Valley, and Dharamkot village stays.",
  quickStats: [
    { label: "McLeodganj altitude", value: "1,457m", icon: "🏔️" },
    { label: "Triund altitude", value: "2,842m", icon: "⛰️" },
    { label: "From Dehradun", value: "270 km", icon: "🚗" },
    { label: "Triund trek", value: "9 km one way", icon: "🥾" },
    { label: "Camping permit", value: "Rs 50-100", icon: "⛺" },
    { label: "Best months", value: "Sep-Nov", icon: "📅" },
  ],
  intro: "Let me clear something up before anything else. When most people book a trip to McLeodganj on a travel app, they are actually searching for Dharamshala. When they book Dharamshala, they often land in the lower town and wonder why it looks nothing like the photos. These are two separate places, 10 km apart in altitude and character, and the confusion wastes people's first day here.\n\nLower Dharamshala sits at 1,457m. It is the Kangra district headquarters - government offices, bus stand, markets, a hospital, a cricket stadium. McLeodganj is the upper town, further into the hills, and that is where the Tibetan quarter, the Namgyal Monastery, the backpacker hostels, the trekking trailheads, and the cafes are. If your plan involves Triund, the Dalai Lama's temple, or any serious time outdoors, you want McLeodganj.\n\nI have done Triund twice - once as a day trek, once with an overnight camp in October. The overnight version is categorically different.",
  sections: [
    { id: "dharamshala-vs-mcleodganj", title: "Dharamshala vs McLeodganj - what is actually different", icon: "📍",
      content: "Lower Dharamshala at 1,457m is the district admin town. HRTC buses from Delhi and Dehradun land here. Budget lodges, North Indian dhabas, the HPCA stadium, Chamunda Devi temple 5 km away. Useful for arrivals and bus changes.\n\nMcLeodganj at 1,457-1,600m, 10 km up the hill, is the Tibetan cultural hub and tourist base. Wide accommodation range from Rs 300 dorm beds to Rs 4,000 hotels, Tibetan restaurants and Israeli cafes, Namgyal Monastery and Tsuglagkhang Complex, Triund trailhead 2 km from central square.\n\nThe taxi between them costs Rs 150-200 by shared auto or Rs 400-500 by cab. If you arrive by HRTC bus from Delhi or Dehradun, you land at lower Dharamshala bus stand. Take a shared auto or taxi straight up to McLeodganj - 20-25 minutes." },
    { id: "drive-from-dehradun", title: "The drive from Dehradun", icon: "🚗",
      content: "Route: Dehradun - Paonta Sahib - Nahan - Bilaspur - Hamirpur - Kangra - Dharamshala on NH-503 and NH-154 through Himachal's lower hills. Not a dramatic mountain drive for most of the way - a steady highway through green river valleys and small HP towns. The mountain character starts only in the last 40 km when the Dhauladhar range comes into view from Kangra district.\n\nKey distances: Dehradun to Paonta Sahib 45 km (1 hour), Paonta to Bilaspur 120 km (2.5 hrs), Bilaspur to Hamirpur 40 km (45 min), Hamirpur to Kangra 45 km (1 hour), Kangra to Dharamshala 18 km (30-35 min). Total: 270 km, 6-7 hours including stops.\n\nLeave Dehradun by 5 AM and you reach Dharamshala by noon. The Paonta Sahib route is more reliable than going through Chandigarh - less city traffic and a cleaner highway run through HP.\n\nWithout a car: HRTC Volvo runs Delhi to Dharamshala overnight from ISBT Kashmere Gate, departs 9-10 PM, arrives 6-7 AM. From Dehradun, take the 7 AM HRTC ordinary bus from Dehradun ISBT (arrives Dharamshala 3-4 PM, Rs 350-400). Private taxi Dehradun to Dharamshala Rs 3,500-4,500 one-way." },
    { id: "mcleodganj-things-to-do", title: "McLeodganj - what to actually do", icon: "🏯",
      content: "Namgyal Monastery and Tsuglagkhang Complex: 5-minute walk from McLeodganj central square. Three things in one: the main temple, the Tibet Museum, and the Kalachakra temple. Entry free to all sections. Namgyal is the Dalai Lama's personal monastery - when His Holiness is in residence, large public teachings happen in the courtyard, announced 2-4 weeks in advance on namgyal.net. Outside teaching periods, still worth an hour. The main hall has a 5-meter gilded Buddha statue flanked by Chenrezig and Padmasambhava. No photography inside prayer halls.\n\nBhagsu and the waterfall: 2 km from McLeodganj main chowk. Bhagsu Nag is a functioning Shiva shrine with a natural spring. A 1.5 km trail goes up to Bhagsu waterfall - 30 minutes up, 20 minutes down. Crowded on weekends with Chandigarh day-trippers, so go early.\n\nDharamkot rock climbing: 5 km from McLeodganj, a smaller village above Bhagsu. Local operators run single-pitch courses on Dhauladhar granite, Rs 500-800 per person for 2 hours with equipment.\n\nYoga and meditation: 20+ centers in McLeodganj. Drop-in classes Rs 300-500, structured 5-10 day courses Rs 2,000-8,000. Tushita Meditation Centre above Dharamkot is the most established - 10-day intro courses in Tibetan Buddhism, booking fills months in advance.\n\nTibetan cooking: Lha teaching center near TCV school runs cooking classes at Rs 800 per session. Make momos, thukpa, tsampa preparations. 2-3 hour session, you eat what you make." },
    { id: "triund-trek", title: "Triund Trek - the main event", icon: "🥾",
      content: "Trailhead: Most people start from McLeodganj and walk through Bhagsu and Dharamkot to reach Galu Devi Temple, the official trailhead. McLeodganj to Galu Devi is 2 km on paved road. From Galu Devi, the forest trail begins.\n\nTotal distance: 7 km from Galu Devi (9 km if you walk from McLeodganj main chowk). Altitude gain: 1,457m to 2,842m - 1,385m gain from McLeodganj. Time: 4-5 hours up for average fitness, 3 hours down. Trail surface: forest path, stone steps in sections, exposed rocky ridge for the last 1.5 km.\n\nThree segments: the lower 3 km through oak and rhododendron forest is the steepest - a sustained 45-60 degree slope. Snowline Camp at 2,200m opens into a clearing with 4-5 chai shops selling Maggi and biscuits - last reliable water source and food stop. From Snowline, the gradient eases as the trail traverses the ridge. The final 1.5 km is on open rocky ground with direct views of the Dhauladhar above and the Kangra valley below.\n\nPhysical demand: Triund is marketed as easy. It is not. 1,385m of altitude gain over 7 km is a solid day for anyone not used to climbing. Beginners should budget 5-6 hours up and take it slow. See the acclimatize-above-3000m guide - Triund sits just below 3,000m but the rate of climb is fast enough that some people feel it." },
    { id: "day-vs-overnight", title: "Day trek vs overnight camping", icon: "⛺",
      content: "Day trek: Rs 200-400 (food and water on trail), Dhauladhar from the ridge in daylight, high physical demand (10+ hours round trip with breaks), no permit needed. Good if you have only one day.\n\nOvernight camp: Rs 800-1,500 (camping permit + tent rental or own tent + food), Dhauladhar at sunset, night sky, dawn light on snow - completely different experience, moderate physical demand spread over 2 days, HP Forest Dept camping permit required (Rs 50-100/person, max 80-100 permits/night). The real Triund experience.\n\nCamping permit issued by HP Forest Department at Dharamshala or McLeodganj forest office, or sometimes at a trail checkpoint. Only 80-100 permits issued per night to manage overcrowding. Check hpforest.gov.in or visit the forest range office near Bhagsunag road in the morning - no reliable centralized online booking as of 2026.\n\nTent rental Rs 300-500/night for a 2-person tent from McLeodganj shops. Bring or rent a sleeping bag - temperature at Triund drops to 5-10C in summer nights, lower in October.\n\nMy October overnight: camped about a week after Dussehra. Campsite half-full, maybe 15 tents. Ate at one of the small dhaba setups at the top (dal rice Rs 150/plate, fair given someone carried everything up there). At 3 AM, a cloud that had been sitting on the ridge all evening cleared. The Dhauladhar snowline was maybe 300 meters above us, snow picking up enough starlight that the whole ridge glowed without any torch. The Kangra valley was invisible below. I stood there for 20 minutes before it got cold enough to go back in. You do not see that on a day trip." },
    { id: "indrahar-pass", title: "Indrahar Pass - the advanced route", icon: "⛰️",
      content: "Triund is not the end of the trail. From Triund's ridge, serious trekkers continue north and up toward Indrahar Pass at 4,342m - the crossing point through the Dhauladhar into Chamba district.\n\n3-day route (recommended): Day 1 McLeodganj to Triund (7 km, camp at 2,842m). Day 2 Triund to Lahesh Cave or Laka Got (camp at approximately 4,000m, 8 km). Day 3 Laka Got to Indrahar Pass (4,342m) and back to McLeodganj (15 km, long day). Total round trip: 28 km from McLeodganj.\n\nThe Triund to Laka Got route crosses boulder fields and high-altitude meadows with significantly reduced trail marking. Lahesh Cave is a natural rock overhang that provides shelter - no fixed camp infrastructure, bring your own tent and gear regardless.\n\nTechnical difficulty: The pass itself requires no technical climbing in September-October when the approach is dry. In June-July, the upper section carries snow and an ice axe is strongly recommended for the steep final approach. October is the most reliable for non-technical trekking - dry ground, stable weather, good visibility.\n\nAltitude reality: at 4,342m, Indrahar Pass requires genuine acclimatization. The gain from McLeodganj (1,457m) to the pass (4,342m) is 2,885m over 14 km - steeper than most Himalayan passes counted as moderate. Anyone who has had issues at lower altitudes should read the acclimatize-above-3000m guide carefully before committing. At Laka Got at 4,000m, October nights drop below freezing - the packing-4000m guide applies here." },
    { id: "when-to-go", title: "When to go", icon: "📅",
      content: "March-May: snow melting on Triund ridge, wildflowers in the oak forest, trail can be muddy in lower sections. Cool at altitude, pleasant in town. Good window.\n\nJune: last good month before monsoon arrives. Triund is fine but check the forecast daily. Indrahar Pass in June has significant snow - technical gear needed.\n\nJuly-August (monsoon): avoid. The Triund trail has active leeches from the tree line up to Snowline Camp. Rocks are slippery. Clouds block the Dhauladhar views for days at a time. The whole point of Triund is the ridge view - in monsoon, that view is often a white wall of cloud. See the monsoon-routes guide for traveling in Himachal in July-August.\n\nSeptember-October: the best window. Post-monsoon sky is clear, the Dhauladhar gets fresh snow from late September, trail is dry, temperatures cool but comfortable. October is peak trekking season and camping spots at Triund fill up - get your permit early. This is when I went, and I would go back in October every time.\n\nNovember: cold arrives. Triund nights drop to 0C and below. Snowfall possible on the ridge from mid-November. Indrahar Pass closes for winter.\n\nDecember-February: Triund accessible in winter but requires experience in snow and cold. Camping permits still issued. Not recommended for first-time trekkers. Lower Dharamshala and McLeodganj town function year-round." },
    { id: "budget", title: "Budget breakdown", icon: "💰",
      content: "Accommodation in McLeodganj: dorm bed Rs 300-600/night (backpacker hostels around the square and on Temple Road), guesthouse room Rs 700-1,500/night, hotel with views Rs 2,000-4,000/night.\n\nFood: Tibetan restaurant (momos, thukpa, rice plates) Rs 100-200/meal, Israeli cafe style (shakshuka, hummus plates, good coffee) Rs 150-250/meal, bakeries and cafes Rs 50-100 for coffee and bun.\n\nTriund trek budget: camping permit Rs 50-100/person, tent rental Rs 300-500/night, sleeping bag rental Rs 150-250/night, trail food (chai, Maggi, meals at Snowline and top) Rs 300-500/day, porter optional Rs 800-1,200/day.\n\nCash and ATMs: McLeodganj has 3-4 ATMs near the main square. Most guesthouses accept UPI. Restaurants and trekking shops vary - carry Rs 2,000-3,000 in cash before heading to the trail. See the atm-cash-guide for what to expect in smaller HP towns." },
    { id: "lower-dharamshala", title: "Dharamshala's other side - the lower town", icon: "🏛️",
      content: "Most trekking guides ignore lower Dharamshala entirely. A few things worth knowing.\n\nHPCA Stadium: the Himachal Pradesh Cricket Association stadium at 1,457m is the highest international cricket ground in India. Sits on a ridge with the Dhauladhar visible directly behind the sightscreen. If there is a match during your visit, tickets are at the HPCA office. Even without a match, the viewpoint outside is one of the best in the valley for photographing the range behind the town.\n\nChamunda Devi Temple: 5 km from lower Dharamshala toward Palampur. Dedicated to Chamunda Devi, with a gorge view below the complex. Local bus (Rs 15-20) or auto.\n\nKangra Fort: 20 km from lower Dharamshala toward Kangra town. One of the largest forts in the Himalayas by perimeter. ASI-maintained. Entry Rs 25 for Indian nationals." },
    { id: "practical-notes", title: "Practical notes - network, medical, altitude", icon: "🛟",
      content: "Mobile network: Jio and Airtel both work in McLeodganj and on the Triund trail up to approximately 2,500m. Above that, connectivity drops. BSNL has slightly better coverage on HP ridges.\n\nMedical: Dharamshala has a district hospital in the lower town. McLeodganj has two small clinics. For anything serious, Kangra (20 km) or Pathankot (90 km) are the nearest larger facilities. Carry a basic first aid kit on the trail.\n\nAltitude sensitivity: Triund at 2,842m is below the threshold where acute mountain sickness is common, but rapid ascent from 1,457m in 4-5 hours can cause headaches. Drink water consistently on the trail - minimum 2 liters on the ascent. If you have had altitude issues before at 2,500-3,000m, take an extra rest day in McLeodganj before the trek.\n\nGetting around: McLeodganj has two parallel main streets - the road leading to Bhagsu and the road up toward Dharamkot. Everything is walkable from the central square. For Bhagsu (2 km), Galu Devi trailhead (2 km), and Dharamkot (5 km), walk or take a shared auto on fixed routes for Rs 15-30. The main drag has a traffic restriction for larger vehicles, making McLeodganj significantly more walkable than most Himalayan tourist towns.\n\nOfficial HP Tourism: hptourism.gov.in has official accommodation listings and transport schedules." },
  ],
  weatherPoints: [
    { location: "Lower Dharamshala", altitude: 1457, temp: 22, weather: "☀️" },
    { location: "McLeodganj", altitude: 1600, temp: 18, weather: "🌤️" },
    { location: "Snowline Camp", altitude: 2200, temp: 12, weather: "⛅" },
    { location: "Triund Ridge", altitude: 2842, temp: 8, weather: "🌥️" },
  ],
  routes: [
    { from: "Dehradun", to: "Dharamshala", status: "open", note: "270 km via Paonta Sahib, 6-7 hrs" },
    { from: "Delhi", to: "Dharamshala", status: "open", note: "HRTC Volvo overnight, Rs 800-1,200" },
    { from: "Dharamshala", to: "McLeodganj", status: "open", note: "10 km uphill, 20-25 min by auto" },
    { from: "McLeodganj", to: "Triund (via Galu Devi)", status: "open", note: "9 km trek, 4-5 hrs up" },
  ],
  checklist: [
    { category: "Triund essentials", items: [
      { name: "Trekking shoes (waterproof)", essential: true },
      { name: "Headlamp + spare batteries", essential: true },
      { name: "Fleece or down mid-layer", essential: true },
      { name: "Rain shell / poncho", essential: true },
      { name: "Trekking poles", essential: false },
      { name: "Water bottle (2L minimum)", essential: true },
      { name: "Cash Rs 2,000-3,000", essential: true },
    ] },
    { category: "Overnight camp additions", items: [
      { name: "Sleeping bag (3-season)", essential: true },
      { name: "Tent (or rent in McLeodganj)", essential: true },
      { name: "Camping permit from HP Forest Dept", essential: true },
      { name: "Power bank", essential: true },
      { name: "Warm hat and gloves (Oct onwards)", essential: true },
    ] },
    { category: "Indrahar Pass additions", items: [
      { name: "4-season sleeping bag", essential: true },
      { name: "Ice axe (Jun-Jul snow)", essential: false },
      { name: "Diamox (consult doctor)", essential: false },
      { name: "Extra food for 3 days", essential: true },
      { name: "Topo map / offline GPS", essential: true },
    ] },
  ],
  faq: [
    { q: "Is Triund trek open in winter?", a: "The trail is physically accessible in winter (December-February) and the forest department still issues camping permits. However, snow on the upper section makes it significantly harder and colder - Triund nights in December drop below 0C. Bring a 4-season sleeping bag and expect the last 2 km to be on packed snow. Not suitable for first-time trekkers without cold-weather experience." },
    { q: "Do I need a guide for Triund?", a: "No. The trail from Galu Devi Temple to Triund is clear, well-worn, and marked with chai shops at intervals. A guide is useful for Indrahar Pass, where trail markings above Triund become sparse and weather can close in fast. For Triund itself, a guide is unnecessary." },
    { q: "Can I see the Dalai Lama in McLeodganj?", a: "When His Holiness is in residence and conducting public teachings, yes - but it requires prior registration through the Security Office of the Dalai Lama. Teachings are announced on namgyal.net 2-4 weeks in advance. If no teaching is scheduled, a casual sighting is possible but not something you can plan for. His Holiness travels internationally frequently and is not always in residence." },
    { q: "How far is McLeodganj from Dharamshala bus stand?", a: "10 km by road, about 20-25 minutes by auto or taxi. The lower Dharamshala bus stand is where HRTC state buses and most private buses from Delhi, Chandigarh, and Pathankot drop you. Autos run to McLeodganj for Rs 150-200 shared, Rs 400-500 for a full cab. A local bus also runs this route for Rs 15-20." },
    { q: "Is Triund safe for beginners?", a: "Yes, with the right footwear and a reasonable pace. The trail is not technical and no prior trekking experience is required. What catches beginners is the sustained gradient - there is no flat relief on the lower section, just uphill for 3 km. Take your time, drink water, stop at Snowline Camp for a break. The descent is harder on knees than the ascent - trekking poles are helpful but not mandatory." },
    { q: "What is the best time to visit Dharamshala?", a: "September to November is the most reliable window for clear skies, dry trails, and comfortable temperatures in town (15-22C in the day, 8-12C at night in October). March to June also works well and sees wildflowers in the forest sections of the Triund trail. Avoid July-August for any trekking - monsoon makes the trail slippery and the views you came for are usually hidden behind cloud." },
    { q: "How many days do you need for Dharamshala and Triund?", a: "Minimum 3 full days: Day 1 arrive, settle, explore McLeodganj and Namgyal Monastery. Day 2 trek to Triund and camp overnight. Day 3 descend, afternoon free in town. For Indrahar Pass, add 2-3 more days and plan the route separately. If you want both the cultural experience and the trek without feeling rushed, 4-5 days is comfortable." },
  ],
  emergency: [
    { name: "Dharamshala District Hospital", number: "01892-222037" },
    { name: "McLeodganj Police", number: "01892-221483" },
    { name: "HP Forest Department (Triund permits)", number: "01892-222887" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [],
};
