import type { DestinationData } from "./types";

export const ladakh: DestinationData = {
  slug: "ladakh",
  name: "Ladakh",
  tagline: "Manali-Leh and Srinagar-Leh highway logistics for bikers and road trippers",
  region: "Ladakh UT",
  state: "Ladakh",
  type: "adventure",
  altitude: 3524,
  temp: 12,
  weather: "Clear and cold",
  season: "June to September",
  duration: "7-12 days",
  budget: { min: 10000, max: 35000 },
  heroGradient: "linear-gradient(150deg,#1a2a4a,#2a5a7a 60%,#3a3a2a)",
  metaTitle: "Ladakh Road Trip 2026: Manali-Leh Route, Permits & Checklist | TravelBoa",
  metaDescription: "Ladakh bike and road trip guide. Manali-Leh and Srinagar-Leh routes, high pass acclimatization, ILP permits, fuel stops, and complete gear checklist from Dehradun.",
  quickStats: [
    { label: "Leh altitude", value: "3,524m", icon: "🏔️" },
    { label: "Highest pass", value: "Tanglang La 5,328m", icon: "⛰️" },
    { label: "Best month", value: "September", icon: "📅" },
    { label: "Budget (bike)", value: "Rs 12K-18K", icon: "💰" },
    { label: "Duration", value: "7-12 days", icon: "⏱️" },
    { label: "Permits", value: "PAP required", icon: "📋" },
  ],
  intro: "The first decision anyone planning a Ladakh trip gets wrong is treating both highway approaches as interchangeable. They are not. Manali-Leh (NH-3, 479 km) and Srinagar-Leh (NH-1, 434 km) have different opening dates, different altitude profiles, different road quality, different fuel stop reliability, and different scenic character. Which one you take first - and whether you loop both - shapes the entire trip.\n\nI drove the Manali-Leh highway on a Royal Enfield Himalayan and returned via Srinagar-Leh a week later. The two roads felt like different countries. This is a route guide, not a mood piece. If you want to know how many kilometers between fuel pumps and whether the Baralacha La section is rideable after June 10, read on.",
  sections: [
    {
      id: "manali-leh",
      title: "Route 1: Manali to Leh (NH-3)",
      icon: "🛣️",
      content: "Total distance: 479 km. Recommended 2 riding days with overnight at Jispa.\n\nDay 1: Manali to Jispa (114 km). Start from Manali at 2,050m. Rohtang Pass at 3,978m or bypass via Atal Tunnel (no permit needed). Enter Lahaul Valley. Stock fuel at Keylong (last proper station). Sleep at Jispa (3,180m) - HPTDC guesthouses and camps available.\n\nDay 2: Jispa to Leh (365 km). Start before 6 AM. Cross Baralacha La (4,890m) before noon - afternoon storms common. Through Sarchu (4,290m) and three more passes above 4,700m including Tanglang La (5,328m). Emergency fuel at Sarchu camps at Rs 150-200/litre. Arrive Leh by evening.\n\nDo NOT attempt Manali to Leh in one day. The altitude gain is dangerous and the road after dark is dangerous.",
    },
    {
      id: "srinagar-leh",
      title: "Route 2: Srinagar to Leh (NH-1)",
      icon: "🛣️",
      content: "Total distance: 434 km. 2 days with overnight at Kargil. Opens earlier than Manali-Leh (usually early May).\n\nDay 1: Srinagar to Kargil (204 km). Through Kashmir valley to Sonamarg (2,800m), over Zoji La (3,528m) - narrow, no guardrails, shared with trucks. Cross early to avoid traffic. Through Drass (second-coldest inhabited place on earth). Fuel at Drass. Sleep at Kargil (2,676m) - proper town with ATMs, restaurants, fuel.\n\nDay 2: Kargil to Leh (230 km). Over Fotu La (4,108m), past Lamayuru monastery (worth 30 min stop), through Basgo and Nimmu into Leh. Better road surface than Manali-Leh overall and lower maximum altitude - easier for first-timers.\n\nFuel on this route is more reliable: Sonamarg, Drass, Kargil, Lamayuru.",
    },
    {
      id: "acclimatization",
      title: "Acclimatization in Leh",
      icon: "🫁",
      content: "Leh at 3,524m requires mandatory rest.\n\nDay 1 in Leh: Do almost nothing. Walk slowly. Drink water. Eat light. No bike rides, no alcohol.\n\nDay 2: Short acclimatization drive - Hall of Fame museum or Shanti Stupa (both within 5 km). Still rest heavily.\n\nDay 3 onwards: Day trips to Magnetic Hill and nearby monasteries. Test how you feel before attempting passes.\n\nCommon mistake: arriving in Leh and immediately riding to Khardung La (5,359m) the next morning. That is 1,835m above Leh. Serious AMS risk. Spend 2 full days in Leh first.\n\nSee the full acclimatization guide at /guides/acclimatize-above-3000m for Diamox dosage and detailed protocol.",
    },
    {
      id: "permits",
      title: "Permits: Protected Area Permit (PAP)",
      icon: "📋",
      content: "Indian citizens need PAP for: Nubra Valley (including Diskit, Hunder), Pangong Tso (via Chang La), Hanle (astronomy village), Dah-Hanu (Aryan village area).\n\nCost: Rs 400 per person per area. Apply online at lahdcleh.nic.in or at the District Collectorate in Leh. Processing: 24-48 hours online, same day at office. Documents: Aadhaar copy, passport photo, itinerary dates. Validity: 7 days per area.\n\nKhardung La itself: No permit needed. Foreigners: Additional FRRO registration and separate ILP required.\n\nSee /guides/char-dham-epass for the full permit comparison including Spiti ILP.",
    },
    {
      id: "day-trips",
      title: "Day trips from Leh",
      icon: "🏍️",
      content: "Khardung La (5,359m) - 39 km from Leh. Second-highest motorable pass. Military-maintained road, 1.5-2 hours to reach. Temperature 0-8C even in July. Continue 125 km to Nubra Valley or turn back for a half-day ride.\n\nNubra Valley - 125 km from Leh via Khardung La. Double-humped Bactrian camels on sand dunes. Valley floor at 3,050m. Two nights ideal. PAP required.\n\nPangong Tso - 160 km from Leh via Chang La (5,360m). Famous lake at 4,350m. 5-6 hour drive. Camp one night at basic tents Rs 800-1,500. PAP required.\n\nMagnetic Hill and Gurudwara Pathar Sahib - 30 km from Leh. Quick half-day trip. Free langar at Pathar Sahib.",
    },
    {
      id: "fuel",
      title: "Fuel station map",
      icon: "⛽",
      content: "Manali-Leh: Manali (last private pumps), Keylong (government depot, unreliable hours), Sarchu (emergency from camps at Rs 150-200/litre), Leh (multiple, reliable).\n\nSrinagar-Leh: Srinagar (multiple), Sonamarg (one pump), Drass (one pump), Kargil (multiple, reliable), Leh.\n\nFrom Leh outward: No pump at Nubra, Pangong, or Hanle. Always leave Leh with a full tank.\n\nRule: Always leave Leh full. Every day trip, fill the tank before leaving, even if you filled it yesterday. From Manali to Leh tank-to-tank is 479 km - manageable for bikes with 12L+ tanks plus the Keylong fill-up. Carry 3L extra to be safe.",
    },
    {
      id: "best-months",
      title: "Best months to visit",
      icon: "📅",
      content: "June: Roads open mid-to-late May (Manali-Leh) or early May (Srinagar-Leh). Clear and cold. Leh 5-25C. Best riding conditions.\n\nJuly: Monsoon affects Manali-Leh road. Leh itself gets almost no rain. Srinagar-Leh more reliable.\n\nAugust: Peak tourist season. Leh hotels book out. Good visibility.\n\nSeptember: The best month. Monsoon retreating. Clear skies. Fewer crowds. Roads fully open. Highly recommended.\n\nOctober: Late season. Cold. Snow possible on high passes after mid-October. Not for first-timers.",
    },
    {
      id: "budget",
      title: "Budget breakdown",
      icon: "💰",
      content: "Bike (own): Rs 12,000-18,000 total for 10 days including fuel, accommodation, food, permits.\n\nRented bike (Manali): Rs 18,000-28,000 total. RE Himalayan Rs 1,200-1,800/day.\n\nShared taxi: Rs 14,000-20,000 total.\n\nPrivate car: Rs 22,000-35,000 total.\n\nVolvo bus (HRTC): Rs 10,000-15,000 total. Manali to Leh Rs 1,200-1,800 one way, 18-20 hours.\n\nFlying to Leh from Delhi: Rs 3,000-8,000. Saves 3 days of road time. Rentals from Leh available.\n\nLeh has the only reliable ATMs on the circuit. Carry Rs 10,000-15,000 cash for day trips.",
    },
    {
      id: "packing",
      title: "What to pack",
      icon: "🎒",
      content: "Riding jacket with CE armor (not a trekking jacket). See /gear/jackets-ladakh for specific picks.\n\nTwo pairs of gloves: warm/insulated for passes, mesh for valley. See /gear/riding-gloves-ladakh.\n\nBase thermals for the 5C to 35C temperature swing. 3L+ spare fuel container for Manali-Leh road. First aid kit with Diamox, Ibuprofen, ORS. Downloaded offline maps (Google Maps works offline, Maps.me for coverage). Spare inner tubes if riding tube-tyre bike.\n\nSee /guides/packing-4000m for the complete high-altitude packing list.",
    },
  ],
  weatherPoints: [
    { location: "Leh", altitude: 3524, temp: 12, weather: "☀️" },
    { location: "Khardung La", altitude: 5359, temp: 2, weather: "💨" },
    { location: "Nubra Valley", altitude: 3050, temp: 28, weather: "🌡️" },
    { location: "Pangong Tso", altitude: 4350, temp: 8, weather: "☀️" },
  ],
  routes: [
    { from: "Manali", to: "Leh (NH-3)", status: "open", note: "479 km, 2 days" },
    { from: "Srinagar", to: "Leh (NH-1)", status: "open", note: "434 km, 2 days" },
    { from: "Leh", to: "Nubra (Khardung La)", status: "open", note: "PAP required" },
    { from: "Leh", to: "Pangong (Chang La)", status: "open", note: "PAP required" },
  ],
  checklist: [
    {
      category: "Riding gear",
      items: [
        { name: "CE-rated riding jacket", essential: true },
        { name: "Insulated gloves (passes)", essential: true },
        { name: "Mesh gloves (valleys)", essential: true },
        { name: "Riding boots", essential: true },
        { name: "Helmet with visor", essential: true },
      ],
    },
    {
      category: "Clothing",
      items: [
        { name: "Thermal base layers x2", essential: true },
        { name: "Fleece mid-layer", essential: true },
        { name: "Down jacket (camp)", essential: true },
        { name: "Waterproof shell", essential: true },
        { name: "Quick-dry trousers x2", essential: true },
      ],
    },
    {
      category: "Bike essentials",
      items: [
        { name: "Spare fuel can (3L+)", essential: true },
        { name: "Spare inner tubes", essential: true },
        { name: "Puncture repair kit", essential: true },
        { name: "Basic tool kit", essential: true },
        { name: "Bungee cords/ROK straps", essential: false },
      ],
    },
    {
      category: "Health & safety",
      items: [
        { name: "Diamox 250mg", essential: true },
        { name: "First aid kit", essential: true },
        { name: "Sunscreen SPF50", essential: true },
        { name: "Pulse oximeter", essential: false },
        { name: "ORS sachets x10", essential: true },
      ],
    },
    {
      category: "Electronics",
      items: [
        { name: "Power bank 20,000 mAh", essential: true },
        { name: "Offline maps downloaded", essential: true },
        { name: "Phone mount for bike", essential: true },
        { name: "Headlamp", essential: false },
      ],
    },
    {
      category: "Documents",
      items: [
        { name: "PAP permit (printed)", essential: true },
        { name: "Aadhaar / ID proof x2", essential: true },
        { name: "Vehicle RC and insurance", essential: true },
        { name: "Bike rental agreement", essential: false },
        { name: "Cash Rs 15,000-20,000", essential: true },
      ],
    },
  ],
  faq: [
    { q: "Which route should I take first - Manali-Leh or Srinagar-Leh?", a: "For bikers, Manali-Leh to Leh and return via Srinagar-Leh creates the best loop. If you can only do one, Manali-Leh is the more challenging and rewarding ride. Srinagar-Leh opens earlier and is better in July-August." },
    { q: "Can I ride to Ladakh on a 150cc bike?", a: "Technically yes, but 150cc bikes struggle above 4,500m due to thin air reducing engine power. RE 350/500cc, Hero Xpulse, or KTM Adventure are standard recommendations." },
    { q: "Is the Manali-Leh road open in June?", a: "Usually from June 10-15. Monitor bro.gov.in for the official opening. Do not attempt before the official announcement." },
    { q: "How much cash should I carry from Leh?", a: "Rs 10,000-15,000 minimum for day trips. No ATMs outside Leh except one intermittent SBI in Diskit. No UPI at Pangong." },
    { q: "Do I need to book Leh accommodation in advance?", a: "In July-August: yes, especially under Rs 1,200/night. In June or September: less urgent. Nubra/Pangong tent camps rarely take advance bookings." },
    { q: "What altitude sickness risk should I expect?", a: "Leh is at 3,524m. Arriving by flight from Delhi is highest-risk - you gain 3,000m in 1 hour. Overland via Manali-Leh gives 2 days of gradual acclimatization. Spend 2 full rest days in Leh before attempting passes." },
    { q: "Can I take a bus from Manali to Leh?", a: "Yes. HRTC Volvo from Manali to Leh in 18-20 hours, Rs 1,200-1,800. Reserve at hrtchp.com at least a week ahead for July-August." },
    { q: "What is the best month for Ladakh?", a: "September. Monsoon retreated, clear skies, fewer crowds, roads fully open, stable weather. June is second best for riding conditions." },
  ],
  emergency: [
    { name: "SNM Hospital Leh", number: "01982-252012" },
    { name: "Police Control Room Leh", number: "01982-252018" },
    { name: "BRO Emergency", number: "1800-180-3474" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [
    { slug: "packing", title: "Ladakh packing checklist", description: "Complete packing list for a Ladakh bike trip" },
  ],
};
