import type { DestinationData } from "./types";

export const manali: DestinationData = {
  slug: "manali",
  name: "Manali",
  tagline: "Gateway town for Ladakh, Spiti, and Lahaul",
  region: "Kullu",
  state: "Himachal Pradesh",
  type: "adventure",
  altitude: 2050,
  temp: 18,
  weather: "Pleasant",
  season: "Year-round (highway Jun-Sep)",
  duration: "2-3 days (staging) or 5-7 days (activity)",
  budget: { min: 3000, max: 15000 },
  heroGradient: "linear-gradient(150deg,#1a3a5a,#2a6a4a 60%,#3a4a2a)",
  metaTitle: "Manali Guide 2026: Gateway to Ladakh, Spiti & Rohtang Pass | TravelBoa",
  metaDescription: "Manali travel guide. Staging town for Manali-Leh highway and Manali-Spiti route. Rohtang Pass permit, Solang Valley, Old Manali cafes, and what to pack for onward trips.",
  quickStats: [
    { label: "Altitude", value: "2,050m", icon: "🏔️" },
    { label: "From Dehradun", value: "530 km", icon: "🚗" },
    { label: "To Leh", value: "479 km", icon: "🛣️" },
    { label: "Best months", value: "Jun, Sep-Oct", icon: "📅" },
    { label: "Budget", value: "Rs 3K-15K", icon: "💰" },
    { label: "ATMs", value: "10+ reliable", icon: "🏧" },
  ],
  intro: "Most people arrive in Manali thinking it is the trip. The snowcapped peaks, the apple orchards, the Beas river cutting through the valley - it looks the part. But if you talk to anyone who has actually been here more than once, the honest answer is the same: Manali is a staging town. It is where you prepare for the harder routes that start here.\n\nThe Manali-Leh highway to Ladakh starts at the north end of town. The Manali-Spiti route via Rohtang Pass begins at the same junction. I drove up from Dehradun on a Royal Enfield Himalayan in late September, planning a Ladakh run before the highway closed. I spent two full days sorting bike paperwork, buying fuel cans, checking the permit system, and eating momos twice a day. On the third morning, I left for Leh before sunrise.",
  sections: [
    { id: "getting-there", title: "Getting to Manali from Dehradun", icon: "🚗",
      content: "530 km via Chandigarh, 10-12 hours by road. The fastest route is Dehradun to Chandigarh (170 km, NH-72A) then Chandigarh to Manali (310 km, NH-21 via Kullu). HRTC Volvo from Chandigarh ISBT to Manali: Rs 800-1,200, 8-9 hours. Overnight Volvo from Delhi ISBT to Manali: Rs 1,200-1,800, 12-14 hours.\n\nFlying: Bhuntar airport (Kullu) is 50 km from Manali. Flights from Delhi Rs 3,000-8,000. Taxi from Bhuntar to Manali Rs 800-1,200." },
    { id: "stay", title: "Where to stay: Old Manali vs Mall Road", icon: "🏨",
      content: "Old Manali: The traveler zone. Guesthouses Rs 500-1,500, cafes, bakeries, gear shops, international crowd. 2 km from Mall Road. This is where bike-trippers and backpackers stay.\n\nMall Road area: More commercial, closer to bus stand. Hotels Rs 800-3,000. Better for families and short stays.\n\nPractical rule: if you are staging for Ladakh or Spiti, stay in Old Manali. The bike rental shops, fuel can sellers, and permit offices are all accessible from here. If you are here for Solang and Rohtang day trips, Mall Road is more convenient." },
    { id: "permits", title: "Permits you need", icon: "📋",
      content: "Rohtang Pass surface road: Permit from SDM Manali, Rs 100 per vehicle. Apply at admis.hp.nic.in. Daily vehicle cap applies. Not needed if using Atal Tunnel.\n\nAtal Tunnel: No permit required for regular vehicles. Free to use.\n\nLadakh PAP: Apply online at lahdcleh.nic.in from Leh, not Manali. You do not need a permit to leave Manali - you need it when you reach Ladakh.\n\nSpiti ILP: For areas beyond Sumdo. Apply via HP government portal. Processing 1-3 days.\n\nSee /guides/char-dham-epass for the full permit comparison." },
    { id: "seasons", title: "Seasonal calendar", icon: "📅",
      content: "March-May: Snow melting, Solang snow activities. Rohtang opens mid-May. Pleasant weather.\n\nJune: Manali-Leh highway opens (usually June 10-15). Best month for Ladakh departure. Clear, warm days.\n\nJuly-August: Monsoon. Valley gets rain. Passes can close temporarily. Tourist crowds thin.\n\nSeptember: Best month. Monsoon retreating, clear skies, highways still open, fewer tourists. My recommended window.\n\nOctober: Cold setting in. Passes start closing late October. Last window for Ladakh.\n\nNovember-February: Snow season. Solang skiing. Highways closed. Manali itself is accessible year-round." },
    { id: "solang", title: "Solang Valley", icon: "🎿",
      content: "14 km from Manali. Cable car (ropeway) to 3,000m - Rs 500-800 return. Snow activities in winter: skiing, snowboarding, tubing. Summer: paragliding Rs 1,500-2,500, zorbing.\n\nThe cable car view is genuinely worth it on a clear day. Go early morning before clouds build. Avoid weekends in May-June when queues reach 2-3 hours." },
    { id: "rohtang", title: "Rohtang Pass as a day trip", icon: "⛰️",
      content: "Rohtang Pass (3,978m) is 51 km from Manali. Day trip possible: leave by 7 AM, return by 4 PM. Permit required for surface road. The Atal Tunnel bypasses the pass but if you want the experience of the pass itself, take the surface road.\n\nSnow on the pass from November to May. In summer, the pass is a crowded tourist spot with snow play areas. The views into Lahaul Valley from the top are the real reward.\n\nBetter option: drive through Atal Tunnel (free, no permit) and explore Sissu waterfall and Keylong in Lahaul Valley as a day trip instead." },
    { id: "rafting", title: "Beas River rafting", icon: "🚣",
      content: "White water rafting on the Beas from Pirdi to Jhiri. 14 km stretch, Grade 2-3 rapids. Rs 500-1,000 per person. 1-1.5 hours. Available April to June and September to October.\n\nLess intense than Rishikesh rafting but the mountain setting is better. Book through your guesthouse or at the Pirdi launch point directly." },
    { id: "food", title: "Food in Manali", icon: "🍜",
      content: "Old Manali cafes: momos, thukpa, Israeli food, Italian. Lazy Dog, Drifter's Cafe, Johnson's Cafe are reliable.\n\nBudget eating: Dhaba thalis on Mall Road Rs 100-150. Tibetan restaurants Rs 80-120 for momos.\n\nBefore Ladakh: eat well in Manali. The food options thin out dramatically after Keylong. Stock up on dry snacks, energy bars, and instant noodles from the shops in Old Manali." },
    { id: "cash", title: "Cash, ATMs, and what to carry north", icon: "🏧",
      content: "Manali has 10+ ATMs from SBI, HDFC, ICICI. All work reliably. This is the last city with full banking before you head north.\n\nFor Ladakh: withdraw Rs 15,000-20,000 minimum. No ATM between Manali and Leh (Keylong has one unreliable SBI).\n\nFor Spiti via Rohtang: withdraw Rs 15,000-20,000. Kaza has one ATM that is frequently empty.\n\nSee /guides/atm-cash-guide for the full town-by-town breakdown." },
    { id: "ladakh-prep", title: "Preparing for Ladakh from Manali", icon: "🏍️",
      content: "Bike rental: RE Himalayan Rs 1,200-1,800/day, RE Classic 350 Rs 800-1,200/day. Multiple shops on Old Manali road. Inspect the bike, check tyres, ask about breakdown support.\n\nFuel cans: 5L jerry cans from hardware shops on Mall Road, Rs 200-400. Carry 5-10L extra for the Manali-Leh stretch.\n\nMechanic check: get the bike serviced in Manali. The next mechanic is Keylong (115 km) or Leh (479 km).\n\nSee /ladakh for the full Manali-Leh highway guide." },
    { id: "budget", title: "Budget breakdown", icon: "💰",
      content: "Budget (Rs 1,500-2,500/day): Old Manali guesthouse Rs 500-900, dhaba meals Rs 300-400/day, one activity Rs 500-800.\n\nMid-range (Rs 3,000-5,000/day): Hotel Rs 1,500-2,500, restaurant meals Rs 600-800/day, two activities Rs 1,500-2,500.\n\nLadakh staging costs: bike rental Rs 1,200-1,800/day, fuel cans Rs 400, permits Rs 100-600, extra supplies Rs 500-1,000. Budget 2-3 days in Manali before departure." },
  ],
  weatherPoints: [
    { location: "Manali", altitude: 2050, temp: 18, weather: "🌤️" },
    { location: "Solang Valley", altitude: 2480, temp: 12, weather: "❄️" },
    { location: "Rohtang Pass", altitude: 3978, temp: 2, weather: "❄️" },
  ],
  routes: [
    { from: "Dehradun", to: "Manali", status: "open", note: "530 km, 10-12 hrs" },
    { from: "Delhi", to: "Manali", status: "open", note: "530 km, 12-14 hrs" },
    { from: "Manali", to: "Leh", status: "open", note: "479 km (Jun-Oct)" },
    { from: "Manali", to: "Kaza (Spiti)", status: "open", note: "Via Rohtang/Kunzum" },
  ],
  checklist: [
    { category: "For Ladakh departure", items: [
      { name: "Cash Rs 15,000-20,000", essential: true },
      { name: "Fuel cans 5-10L", essential: true },
      { name: "Bike serviced and checked", essential: true },
      { name: "Offline maps downloaded", essential: true },
      { name: "Warm layers packed", essential: true },
      { name: "First aid kit with Diamox", essential: true },
    ] },
    { category: "General", items: [
      { name: "Warm jacket", essential: true },
      { name: "Rain gear", essential: true },
      { name: "Power bank charged", essential: true },
      { name: "Sunscreen SPF50", essential: true },
    ] },
  ],
  faq: [
    { q: "How many days should I spend in Manali?", a: "2-3 days if staging for Ladakh or Spiti. 4-5 days if doing Solang, Rohtang, rafting, and exploring. 1 night is too rushed for any purpose." },
    { q: "Is Old Manali safe for solo travelers?", a: "Yes. Old Manali has a large international backpacker community and is generally safe. Standard precautions apply after dark." },
    { q: "When does the Manali-Leh highway open?", a: "Usually June 10-15. Check bro.gov.in for the official opening date. Do not attempt before the announcement." },
    { q: "Can I rent a bike in Manali for Ladakh?", a: "Yes. RE Himalayan Rs 1,200-1,800/day. Multiple shops in Old Manali. Inspect thoroughly before renting. Ask about breakdown support on the highway." },
    { q: "Is Atal Tunnel free?", a: "Yes, free for all regular vehicles. No permit needed. Saves 4-5 hours vs the old Rohtang surface road." },
    { q: "What is the best month for Manali?", a: "September. Clear skies, highways open, fewer tourists, pleasant temperatures. June is second best for Ladakh departure." },
  ],
  emergency: [
    { name: "Manali Civil Hospital", number: "01902-252375" },
    { name: "Manali Police", number: "01902-252126" },
    { name: "HRTC Bus Stand", number: "01902-252323" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [],
};
