import type { DestinationData } from "./types";

export const rishikesh: DestinationData = {
  slug: "rishikesh",
  name: "Rishikesh",
  tagline: "The staging town for every Uttarakhand mountain trip",
  region: "Garhwal",
  state: "Uttarakhand",
  type: "adventure",
  altitude: 372,
  temp: 28,
  weather: "Warm",
  season: "Year-round",
  duration: "1-2 days (transit) or 3-5 days (activity)",
  budget: { min: 1500, max: 10000 },
  heroGradient: "linear-gradient(150deg,#064e3b,#059669 60%,#0d9488)",
  metaTitle: "Rishikesh Travel Guide 2026: Rafting, Yoga, Cafes & Char Dham Base | TravelBoa",
  metaDescription: "Rishikesh guide from a Dehradun local. Best rafting stretches, yoga ashrams, Laxman Jhula, cafe guide, and why this is your staging town for Char Dham and Himalayan treks.",
  quickStats: [
    { label: "Altitude", value: "372m", icon: "🏔️" },
    { label: "From Dehradun", value: "43 km", icon: "🚗" },
    { label: "To Kedarnath", value: "248 km", icon: "🛣️" },
    { label: "Weather", value: "25-38C", icon: "🌡️" },
    { label: "ATMs", value: "20+ reliable", icon: "🏧" },
    { label: "Gear shops", value: "Laxman Jhula area", icon: "🎒" },
  ],
  intro: "Rishikesh confuses people because it gets marketed as two completely different things simultaneously: a yoga and wellness retreat for foreigners and a starting point for Char Dham yatra for Indian pilgrims. Both groups are present in large numbers and have almost no overlap.\n\nFrom Dehradun, I pass through Rishikesh on almost every trip toward the hills. 43 km, about an hour. The town sits at 372m - the last major city before the Himalayas begin in earnest. Beyond Rishikesh, the towns get smaller, the roads narrower, the ATMs less reliable, and the gear selection basically zero.\n\nThis is the guide for people who are passing through with a purpose: who need to stock up, withdraw cash, pick up any forgotten gear, sleep one night, and leave at 4 AM for Kedarnath or Badrinath the next morning.",
  sections: [
    { id: "stay", title: "Where to stay: near ISBT vs Laxman Jhula", icon: "🏨",
      content: "Near ISBT (main town): Best for early morning Char Dham departures. Shared taxis and buses depart from here for Rudraprayag and Guptkashi. 5-minute walk to your 4 AM taxi. Budget hotels Rs 500-1,000 per night. Clean, functional, nothing fancy.\n\nLaxman Jhula area: Best for rafting, yoga, gear shopping, and the traveler scene. 6-8 km north of ISBT. Cafes, gear shops, ashrams. Budget guesthouses Rs 400-800. Mid-range Rs 1,000-2,500.\n\nPractical rule: if you are leaving for Char Dham at 4-5 AM, stay near ISBT. If you have a buffer day for gear and activities, stay near Laxman Jhula." },
    { id: "atm", title: "ATM and cash: do this before you leave", icon: "🏧",
      content: "Rishikesh has 20+ ATMs from SBI, HDFC, ICICI, Axis, and PNB. All work reliably. This is the last city where every ATM machine will have cash and every UPI transaction will process.\n\nWithdraw your full trip budget here. For Kedarnath: Rs 8,000-12,000. For Badrinath: Rs 5,000-8,000. For full Char Dham circuit: Rs 15,000-25,000. For Spiti: Rs 20,000-25,000.\n\nDo not plan to use ATMs beyond Rudraprayag for Kedarnath or beyond Joshimath for Badrinath. See /guides/atm-cash-guide for the town-by-town breakdown." },
    { id: "gear", title: "Gear shops: what is available and where", icon: "🎒",
      content: "Laxman Jhula area: A stretch of 8-10 outdoor gear shops on the road from Ram Jhula to Laxman Jhula. Trekking poles (Rs 300-800), rain ponchos (Rs 100-300), water bottles, headlamps, and basic fleeces. Quality is variable - inspect items before buying.\n\nDecathlon Rishikesh: Smaller than Dehradun but carries the core Quechua and Forclaz range. Good for last-minute base layers, shoes, and rain gear.\n\nDiamox: Available at chemists near ISBT and in the Laxman Jhula area. Ask for Acetazolamide 250mg. Pick it up here rather than hoping to find it in Guptkashi.\n\nWhat you cannot buy in Rishikesh: Quality sleeping bags, CE-rated riding jackets, proper trekking shoes in all sizes. Buy these in Dehradun at Decathlon Rajpur Road or order from Amazon before your trip." },
    { id: "registration", title: "Char Dham registration", icon: "📋",
      content: "Do your Char Dham e-pass registration in Rishikesh, not at the checkpost. The registration counter at ISBT Rishikesh has shorter queues than Sonprayag or Gaurikund.\n\nBetter option: register online at registrationandtouristcare.uk.gov.in before you leave home. It takes 5-10 minutes. Print the e-pass. Carry a printed copy - phone signal is unreliable at checkpoints.\n\nSee /guides/char-dham-epass for the step-by-step process including common rejection reasons." },
    { id: "rafting", title: "Rafting: worth it, but know the operators", icon: "🚣",
      content: "White water rafting on the Ganga is Rishikesh's signature activity. The standard 16 km Shivpuri to Rishikesh stretch takes 2-3 hours, costs Rs 800-1,500 per person, and includes Grade 3-4 rapids.\n\nBook through established operators: Red Chilli, Aquaterra Adventures, or your hotel. Avoid touts at the bridge who quote Rs 300 - they subcontract to operators with questionable safety equipment.\n\nBest months for rafting: September-November (post-monsoon, river is full but controlled) and February-May (clear water, good weather). July-August the river is too high and rafting is suspended.\n\nThe cliff jumping at the end is optional. The photos cost Rs 300-500 extra." },
    { id: "yoga", title: "Yoga ashrams that are actually good", icon: "🧘",
      content: "Parmarth Niketan: The largest ashram on the Ganga. Free evening Ganga Aarti at 6 PM daily - worth attending even if you do not stay. Accommodation Rs 500-2,000 per night including meals and yoga classes.\n\nThe Yoga Institute (Tapovan): Serious yoga training, not tourist yoga. Courses from 3 days to 1 month. Teachers are experienced. Not luxury accommodation.\n\nOshanic International: Popular with foreign travelers. 200-hour yoga teacher training certifications. Good if you want a structured program.\n\nAvoid: Ashrams that promise spiritual enlightenment in weekend workshops at premium prices. The genuine ones are affordable and do not need Instagram marketing." },
    { id: "buffer", title: "The 2-day buffer itinerary before Char Dham", icon: "📋",
      content: "Day 1 (arrival day): Arrive in Rishikesh from Dehradun or Delhi. Check into hotel near ISBT. Withdraw cash. Walk to Laxman Jhula area for any gear purchases. Evening: Ganga Aarti at Parmarth Niketan (6 PM). Early dinner. Sleep by 9 PM.\n\nDay 2 (activity day): Morning rafting (start 8 AM, finish by noon). Afternoon: final gear check, charge all electronics, pack for departure. Buy Diamox if not already sourced. Evening: light dinner, reconfirm morning transport.\n\nDay 3 (departure): Leave at 4-5 AM for Char Dham. This schedule means you arrive at your first mountain stop (Rudraprayag or Guptkashi) by early afternoon with a full day of acclimatization ahead.\n\nOr: skip rafting, use Day 2 for a yoga class and gear shopping, and leave Day 3 rested and prepared." },
    { id: "checklist", title: "What to sort before leaving Rishikesh", icon: "✅",
      content: "Cash: Full trip budget withdrawn from ATM. Diamox: Bought from chemist. E-pass: Registered and printed. Gear: Any missing items from Laxman Jhula shops. Phone: Offline maps downloaded. Power bank: Fully charged. Transport: Morning taxi or bus confirmed at ISBT. Emergency numbers: SDRF 1070, Disaster Helpline 112 saved in phone.\n\nOnce you leave Rishikesh heading toward Rudraprayag, your ability to fix forgotten items drops to near zero. The 43 km between Dehradun and Rishikesh is the last easy shopping stretch." },
  ],
  weatherPoints: [
    { location: "Rishikesh", altitude: 372, temp: 28, weather: "☀️" },
    { location: "Laxman Jhula", altitude: 390, temp: 27, weather: "☀️" },
  ],
  routes: [
    { from: "Dehradun", to: "Rishikesh", status: "open", note: "43 km, 1 hr" },
    { from: "Delhi", to: "Rishikesh", status: "open", note: "240 km, 5-6 hrs" },
    { from: "Rishikesh", to: "Rudraprayag", status: "open", note: "140 km, NH-7" },
    { from: "Rishikesh", to: "Joshimath", status: "open", note: "250 km, NH-7" },
  ],
  checklist: [
    { category: "Before leaving Rishikesh", items: [
      { name: "Cash withdrawn (full trip budget)", essential: true },
      { name: "Char Dham e-pass printed", essential: true },
      { name: "Diamox purchased", essential: true },
      { name: "Offline maps downloaded", essential: true },
      { name: "Power bank fully charged", essential: true },
      { name: "Morning transport confirmed", essential: true },
    ] },
    { category: "Gear check", items: [
      { name: "Rain poncho or waterproof jacket", essential: true },
      { name: "Trekking shoes (broken in)", essential: true },
      { name: "Headlamp with batteries", essential: true },
      { name: "Water bottle 1.5L", essential: true },
      { name: "First aid kit", essential: true },
    ] },
  ],
  faq: [
    { q: "Is Rishikesh worth visiting on its own or just as a transit stop?", a: "Both. For Char Dham pilgrims, it is a 1-night transit stop. For activity travelers, 2-3 days covers rafting, yoga, and the Laxman Jhula scene. The Ganga Aarti at Parmarth Niketan is worth attending either way." },
    { q: "Which is better for gear shopping - Rishikesh or Dehradun?", a: "Dehradun has Decathlon Rajpur Road which is significantly better stocked. Rishikesh has small gear shops near Laxman Jhula for last-minute items. Buy major gear in Dehradun, top up in Rishikesh." },
    { q: "How early do Char Dham taxis leave from ISBT?", a: "Shared taxis and buses for Rudraprayag and Guptkashi start departing at 4-5 AM. The earlier you leave, the better - afternoon arrival at your mountain destination gives acclimatization time." },
    { q: "Is Rishikesh safe for solo female travelers?", a: "The Laxman Jhula and Tapovan area has a large international traveler community and is generally safe. Standard precautions apply - avoid isolated areas after dark, use registered transport." },
    { q: "Can I do rafting and leave for Char Dham the same day?", a: "Technically possible if you raft at 7 AM (finish by 10 AM) and leave immediately. Not recommended - you arrive at your mountain destination late and tired. Better to raft one day, depart the next morning." },
  ],
  emergency: [
    { name: "AIIMS Rishikesh", number: "0135-2462930" },
    { name: "Rishikesh Police", number: "0135-2430245" },
    { name: "SDRF Uttarakhand", number: "1070" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [],
};
