import type { DestinationData } from "./types";

export const shimla: DestinationData = {
  slug: "shimla",
  name: "Shimla",
  tagline: "Colonial hill station and gateway to Spiti via Kinnaur",
  region: "Shimla",
  state: "Himachal Pradesh",
  type: "adventure",
  altitude: 2206,
  temp: 15,
  weather: "Pleasant",
  season: "Year-round",
  duration: "2-3 days (staging) or 4-5 days (full)",
  budget: { min: 2500, max: 12000 },
  heroGradient: "linear-gradient(150deg,#4a2020,#8a4040 60%,#6a3030)",
  metaTitle: "Shimla Guide 2026 - Spiti Staging Town, Kinnaur Route, Toy Train | TravelBoa",
  metaDescription: "Shimla as a destination and Spiti Valley staging town. Kinnaur highway route to Kaza, Kalka-Shimla toy train, Mall Road, budget breakdown, and the Shimla vs Manali comparison for Spiti entry.",
  quickStats: [
    { label: "Altitude", value: "2,206m", icon: "🏔️" },
    { label: "From Dehradun", value: "245 km", icon: "🚗" },
    { label: "To Kaza (Spiti)", value: "415 km", icon: "🛣️" },
    { label: "Toy train", value: "Kalka-Shimla", icon: "🚂" },
    { label: "Budget", value: "Rs 2.5K-12K", icon: "💰" },
    { label: "ATMs", value: "Many, reliable", icon: "🏧" },
  ],
  intro: "Shimla has a dual identity that most travel writing refuses to acknowledge. The tourism-facing version is all Mall Road promenades, Christ Church photography, and Kufri pony rides. The mountain travel version is a fuel stop, a permit checkpoint, and the last city with a functioning ATM before the road narrows into the Sutlej gorge toward Spiti.\n\nI drove from Dehradun to Shimla as the first leg of a Spiti circuit via Kinnaur - 245 km via Paonta Sahib on NH-7, about 5.5 hours with one stop. I stayed two nights in Shimla before pushing on to Narkanda and eventually Kaza. This page handles both functions: what Shimla offers as a destination in its own right, and how to use it as the launch point for one of the most rewarding mountain drives in the country.",
  sections: [
    { id: "getting-there", title: "Getting to Shimla from Dehradun", icon: "🚗",
      content: "245 km via Paonta Sahib (NH-7), 5.5-6 hours. The road is well-maintained throughout. Alternatively: Dehradun to Chandigarh (170 km) then Chandigarh to Shimla (115 km via NH-5).\n\nFrom Delhi: 370 km via Chandigarh, 7-8 hours by road. HRTC Volvo from Delhi ISBT: Rs 800-1,200. Kalka-Shimla toy train from Kalka (after train from Delhi): a scenic 5-hour journey, Rs 300-800.\n\nFlying: Jubbarhatti airport is 23 km from Shimla. Flights from Delhi Rs 3,000-7,000. Taxi to city Rs 500-800." },
    { id: "shimla-destination", title: "Shimla as a destination", icon: "🏛️",
      content: "Mall Road and Ridge: The central promenade. Christ Church at one end, Scandal Point at the other. Evening walking is the main activity - no vehicles allowed. Good for a 2-hour stroll.\n\nJakhu Temple: Hanuman temple at 2,455m, highest point in Shimla. 2 km uphill walk from Ridge. 108-foot Hanuman statue visible from the city. Monkeys are aggressive - secure your belongings.\n\nKufri: 16 km from Shimla. Pony rides, small zoo, snow in winter. Honestly overrated as a tourist spot but the drive through pine forests is pleasant.\n\nChadwick Falls: 7 km from Shimla. Worth a visit during monsoon when the waterfall is at full flow. Dry in winter and spring.\n\nAdvanced Studies Institute (IIAS): The former Viceregal Lodge. Beautiful colonial architecture. Open for tours. The building and grounds are more interesting than most Shimla tourist spots." },
    { id: "spiti-route", title: "Shimla to Kaza via Kinnaur (NH-5)", icon: "🛣️",
      content: "This is the main event for mountain travelers. 415 km from Shimla to Kaza through the Sutlej gorge, Kinnaur Valley, and the cold desert of Spiti.\n\nDay 1: Shimla to Reckong Peo (220 km, 8-9 hours). Through Narkanda (apple country), Rampur, and into the Sutlej gorge. Last reliable ATM at Reckong Peo.\n\nDay 2: Reckong Peo to Kaza (195 km, 8-10 hours). Through Kalpa views, Pooh, Sumdo (ILP checkpoint), Nako, Tabo, and into Kaza.\n\nThe road quality degrades significantly after Reckong Peo. Expect unpaved sections, single-lane stretches, and potential landslide delays in monsoon. See /guides/monsoon-routes for the risk assessment.\n\nThis route is considered safer in monsoon than the Manali-Kaza route via Kunzum La, because it avoids the 4,551m pass entirely." },
    { id: "toy-train", title: "The Kalka-Shimla toy train", icon: "🚂",
      content: "UNESCO World Heritage railway. 96 km from Kalka to Shimla, 102 tunnels, 5-6 hours. Built in 1903.\n\nClasses: First class Rs 600-800, Chair car Rs 300-400, Second class Rs 30. Book on irctc.co.in at least a week ahead for first class.\n\nThe experience is the point, not the speed. Winding through pine forests, crossing bridges, entering tunnels. Best seats: left side going up for valley views.\n\nPractical note: if you are staging for Spiti, the toy train adds a day vs driving from Chandigarh directly. Worth it if you have the time." },
    { id: "staging", title: "Shimla as a Spiti staging town", icon: "🗺️",
      content: "What to do in Shimla before Spiti:\n\nWithdraw cash: Rs 20,000-25,000 for the full Spiti circuit. Shimla ATMs all work. Reckong Peo is the last semi-reliable ATM. Kaza ATM is frequently empty.\n\nFuel up: Full tank before leaving. Next reliable fuel is Reckong Peo (220 km). Carry 5L extra if driving a vehicle with a small tank.\n\nGroceries: Stock dry snacks, instant noodles, biscuits, ORS sachets from Shimla markets. Kaza has basic supplies but limited variety.\n\nDiamox: Buy from Shimla pharmacies if not already sourced. Spiti altitude reaches 4,250m at Chandratal.\n\nOffline maps: Download the full Kinnaur-Spiti stretch. Signal drops out after Reckong Peo.\n\nSee /spiti for the full Spiti Valley guide and /guides/atm-cash-guide for cash logistics." },
    { id: "weather", title: "Weather and the right months", icon: "📅",
      content: "March-May: Pleasant, 15-25C. Apple blossoms. Roads to Spiti may still be snowed in at higher sections.\n\nJune: Warm, 20-30C. Spiti route fully open. Good departure window.\n\nJuly-August: Monsoon. Shimla gets heavy rain. Kinnaur highway has landslide risk. Not recommended for Spiti circuit.\n\nSeptember-October: Best months. Clear skies, pleasant temperatures, Spiti route open and dry. My recommended window.\n\nNovember-February: Cold, 0-10C. Snow possible. Shimla itself is accessible but Spiti route is closed." },
    { id: "budget", title: "Budget breakdown", icon: "💰",
      content: "Budget (Rs 1,500-2,500/day): Budget hotel Rs 600-1,000, dhaba meals Rs 300-400/day, Mall Road walking (free), toy train Rs 300.\n\nMid-range (Rs 3,000-6,000/day): Heritage hotel Rs 2,000-4,000, restaurant meals Rs 600-900/day, Kufri day trip Rs 500.\n\nSpiti staging costs: 2 nights accommodation Rs 1,200-2,000, fuel top-up Rs 1,000-1,500, supplies Rs 500-1,000, cash withdrawal (free). Total Shimla staging: Rs 3,000-5,000." },
    { id: "comparison", title: "Shimla vs Manali for Spiti entry", icon: "⚖️",
      content: "Shimla route (via Kinnaur, NH-5): 415 km to Kaza. Lower maximum altitude (no high pass). Better road surface overall. Safer in monsoon. More towns and fuel stops en route. Takes 2 days.\n\nManali route (via Rohtang/Kunzum La): 200 km to Kaza. Crosses Kunzum La at 4,551m. Unpaved 65 km Batal-Kaza stretch. Higher risk in monsoon. Faster when conditions are good. Takes 1 long day.\n\nRecommendation: Enter via Shimla-Kinnaur, exit via Manali-Rohtang. This gives you the best of both routes and avoids repeating the same road. If doing one-way only, Shimla is the safer bet especially July-September." },
  ],
  weatherPoints: [
    { location: "Shimla", altitude: 2206, temp: 15, weather: "🌤️" },
    { location: "Narkanda", altitude: 2708, temp: 10, weather: "⛅" },
    { location: "Reckong Peo", altitude: 2670, temp: 12, weather: "☀️" },
  ],
  routes: [
    { from: "Dehradun", to: "Shimla", status: "open", note: "245 km, 5.5 hrs" },
    { from: "Delhi", to: "Shimla", status: "open", note: "370 km, 7-8 hrs" },
    { from: "Shimla", to: "Reckong Peo", status: "open", note: "220 km, NH-5" },
    { from: "Shimla", to: "Kaza (Spiti)", status: "open", note: "415 km, 2 days" },
  ],
  checklist: [
    { category: "For Spiti departure", items: [
      { name: "Cash Rs 20,000-25,000", essential: true },
      { name: "Full fuel tank + 5L extra", essential: true },
      { name: "Offline maps downloaded", essential: true },
      { name: "Diamox purchased", essential: true },
      { name: "Dry snacks and supplies stocked", essential: true },
      { name: "Spiti ILP applied (if needed)", essential: true },
    ] },
    { category: "General", items: [
      { name: "Warm jacket", essential: true },
      { name: "Rain gear", essential: true },
      { name: "Power bank charged", essential: true },
      { name: "First aid kit", essential: true },
    ] },
  ],
  faq: [
    { q: "Is Shimla worth visiting on its own?", a: "For 1-2 days, yes. Mall Road, Jakhu Temple, the IIAS building, and the toy train are genuinely interesting. Beyond 3 days, the town runs out of things to do unless you use it as a Spiti launch point." },
    { q: "Which is better for Spiti - Shimla or Manali?", a: "Shimla via Kinnaur is safer (no high pass, better road). Manali via Kunzum is faster when conditions allow. Best plan: enter via Shimla, exit via Manali for the full loop." },
    { q: "Is the toy train worth it?", a: "Yes, if you have 6 hours to spare. The UNESCO heritage railway through 102 tunnels and pine forests is a unique experience. Book first class for the best views." },
    { q: "How much cash for the Spiti circuit from Shimla?", a: "Rs 20,000-25,000 minimum. Last reliable ATM is Reckong Peo. Kaza ATM is unreliable. Carry your full Spiti budget from Shimla." },
    { q: "Can I drive Shimla to Kaza in one day?", a: "Not recommended. It is 415 km on mountain roads with unpaved sections after Reckong Peo. Split it into two days with an overnight at Reckong Peo or Kalpa." },
  ],
  emergency: [
    { name: "IGMC Hospital Shimla", number: "0177-2804251" },
    { name: "Shimla Police", number: "0177-2812344" },
    { name: "HRTC Bus Stand", number: "0177-2658765" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [],
};
