import { DestinationData } from "./types";

export const spiti: DestinationData = {
  slug: "spiti",
  name: "Spiti Valley",
  tagline: "India's cold desert — monasteries, passes, and the most dramatic roads",
  region: "Himachal Pradesh",
  state: "Himachal Pradesh",
  type: "adventure",
  altitude: 3650,
  temp: 10,
  weather: "☀️",
  season: "June – October",
  duration: "8–12 days",
  budget: { min: 12000, max: 40000 },
  heroGradient: "linear-gradient(150deg, #3a3020, #5a5030 60%, #3a5040)",
  quickStats: [
    { label: "Altitude", value: "3,650m (Kaza)", icon: "🏔️" },
    { label: "Highest pass", value: "Kunzum La 4,551m", icon: "⛰️" },
    { label: "Season", value: "Jun – Oct", icon: "🗓️" },
    { label: "Duration", value: "8–12 days", icon: "⏱️" },
    { label: "Budget", value: "₹12K – ₹40K", icon: "💰" },
    { label: "Difficulty", value: "Moderate–Hard", icon: "📊" },
  ],
  intro: `Spiti Valley sits at 3,650m in the trans-Himalayan region of Himachal Pradesh — a cold desert of stark brown mountains, ancient Buddhist monasteries, and some of the most dramatic roads in India. Often called "Little Tibet," this is one of India's most rewarding road trips.

There are two routes in: the Manali side (via Rohtang Pass and Kunzum La) and the Shimla side (via Kinnaur and the Hindustan-Tibet Highway). Most travellers enter from one side and exit the other, making it a circuit. The Manali route opens only after snow clearance in late May/early June. The Shimla route is more stable but has its own rockfall zones.

This guide covers both routes, every key stop, permits, fuel and ATM warnings, and what you actually need to know before driving into one of the most remote inhabited valleys on earth.`,
  sections: [
    { id: "routes", title: "Two routes into Spiti", icon: "🛣️", content: `**Route 1: Manali → Kaza (via Rohtang + Kunzum)**\n\nManali → Rohtang Pass (51 km, 3,978m) → Gramphu → Batal → Kunzum La (4,551m) → Losar → Kaza. Total: ~200 km, 8–10 hours.\n\nThis is the dramatic route. Two high passes, river crossings, and virtually no civilization between Batal and Kaza. The road from Batal to Kunzum is rough gravel — not for the faint-hearted. BRO maintains it but landslides are common.\n\n**Route 2: Shimla → Kaza (via Kinnaur)**\n\nShimla → Narkanda → Rampur → Reckong Peo → Kalpa → Nako → Tabo → Kaza. Total: ~430 km, 2 days.\n\nLonger but more gradual. The Hindustan-Tibet Highway is one of India's most scenic drives. Rockfall zones between Khab and Akpa require caution. More fuel stations and ATMs on this route.\n\n**Recommended circuit:** Enter via Manali, exit via Shimla (or reverse). This way you see both routes without backtracking.` },
    { id: "permits", title: "Permits required", icon: "📋", content: `**Inner Line Permit (ILP):**\n\nRequired for Indian nationals travelling beyond Sumdo towards Tabo/Kaza from the Kinnaur side. Also required for areas near the Tibet border.\n\nGet it from: SDM Office Kaza (free, carry 2 passport photos + ID proof) or SDM Office Reckong Peo.\n\nForeigners need a separate Protected Area Permit from DC Office.\n\n**Rohtang Pass Permit:**\n\nMandatory for crossing Rohtang from Manali side. Apply at: rohtangpermits.nic.in. Cost: ₹100 for petrol vehicles, ₹200 for diesel. Limit: 1,200 vehicles/day. Apply 1–2 days in advance during peak season.\n\n**Chandratal Camping Permit:**\n\nIf camping at Chandratal Lake, you need a camping permit from the Forest Department. Available at Batal or Kaza. Cost: ₹50–100.` },
    { id: "fuel-atm", title: "Fuel, ATM & network", icon: "⛽", content: `**This is the most important section of this guide.**\n\n**Fuel:**\n- Last reliable pump (Manali side): Manali. Fill full tank + carry jerry can.\n- Kaza has a fuel pump but it runs out regularly during peak season. Do NOT rely on it.\n- Last reliable pump (Shimla side): Reckong Peo.\n- There is NO fuel between Manali and Kaza (200 km) and NO fuel between Reckong Peo and Kaza (230 km).\n\n**ATM:**\n- Manali: SBI, HDFC, ICICI — all working.\n- Kaza: SBI ATM only. Empty 50% of the time during peak season.\n- Tabo, Dhankar, Kibber, Langza: No ATM.\n- Reckong Peo: SBI, PNB — reliable.\n- **Carry ₹10,000–15,000 cash minimum.**\n\n**Mobile network:**\n- BSNL postpaid has the best coverage across Spiti.\n- Jio works in Kaza only (patchy).\n- Airtel: almost nothing.\n- Zero signal on the Batal → Losar stretch and most of the Manali route.` },
    { id: "places", title: "Key places to visit", icon: "📍", content: `**Kaza (3,650m):** The administrative capital. Base yourself here for 2–3 days. Market, restaurants, the monastery, and day trips.\n\n**Key Monastery (4,166m):** The iconic Spiti photograph. 1,000-year-old Tibetan Buddhist monastery perched on a hill above the Spiti river. 12 km from Kaza.\n\n**Kibber (4,205m):** One of the highest villages in the world with a motorable road. Kibber Wildlife Sanctuary for snow leopard spotting (rare). Chicham bridge — Asia's highest bridge.\n\n**Chandratal Lake (4,300m):** The "Moon Lake." Crescent-shaped, crystal clear, at the base of barren mountains. Camping only — no structures. Accessible from Batal (14 km rough road). Best at sunrise.\n\n**Dhankar (3,894m):** Hanging monastery on a cliff edge. The old fort is crumbling but stunning. Dhankar Lake is a 2-hour hike above the village.\n\n**Tabo (3,280m):** 1,000-year-old monastery — the "Ajanta of the Himalayas." Cave dwellings above the village. More accessible than Key.\n\n**Langza (4,400m):** Fossil village. You can literally pick up 450-million-year-old marine fossils from the ground. Giant Buddha statue overlooking the valley.\n\n**Pin Valley:** Side valley for serious trekkers. Pin-Bhaba pass connects to Kinnaur.` },
    { id: "budget", title: "Budget breakdown", icon: "💰", content: `**Budget trip (₹12,000–18,000 per person, 10 days):**\n- Bike rental in Manali: ₹800–1,200/day (Royal Enfield)\n- Fuel: ₹3,000–4,000 (full circuit)\n- Stay: ₹500–800/night (homestays)\n- Food: ₹300–500/day (dhabas)\n- Permits: ₹200–300\n\n**Mid-range (₹20,000–30,000):**\n- Shared Innova/Bolero: ₹2,500–3,500/day split 4–5 people\n- Stay: ₹1,000–2,000/night (guesthouses)\n- Food: ₹500–800/day\n- Chandratal camping: ₹500–1,500/night\n\n**Comfort (₹30,000–40,000+):**\n- Private vehicle: ₹3,500–5,000/day\n- Stay: ₹2,000–4,000/night (best available hotels)\n- Food: ₹800–1,200/day` },
    { id: "safety", title: "Safety & altitude", icon: "⚠️", content: `**Altitude sickness is the biggest risk in Spiti.** Kaza is at 3,650m. Kunzum La is at 4,551m. Chandratal is at 4,300m. Symptoms: headache, nausea, breathlessness, insomnia.\n\n**Prevention:** Acclimatize at Manali (2,050m) for a day. If coming from Shimla side, the gradual climb helps. Carry Diamox. Stay hydrated. Avoid alcohol at altitude. Don't rush.\n\n**Road safety:** The Manali–Kaza road is among the most dangerous in India. Water crossings (nallahs), loose gravel, no guardrails, 1,000+ foot drops. Drive slow. Don't drive after dark. Check BRO updates before Batal–Kunzum section.\n\n**Weather:** Temperature drops to 0–5°C at night even in July. Snow possible at Kunzum/Chandratal in June and September. Carry layers.\n\n**Medical:** PHC at Kaza. Nearest hospital: Reckong Peo (6 hours) or Manali (8 hours). Carry a complete medical kit.` },
  ],
  weatherPoints: [
    { location: "Manali", altitude: 2050, temp: 18, weather: "⛅" },
    { location: "Rohtang", altitude: 3978, temp: 2, weather: "❄️" },
    { location: "Kaza", altitude: 3650, temp: 10, weather: "☀️" },
    { location: "Kibber", altitude: 4205, temp: 4, weather: "☀️" },
    { location: "Tabo", altitude: 3280, temp: 14, weather: "☀️" },
    { location: "Kalpa", altitude: 2960, temp: 15, weather: "⛅" },
  ],
  routes: [
    { from: "Manali", to: "Rohtang Pass", status: "open", note: "Clear" },
    { from: "Rohtang", to: "Batal", status: "partial", note: "BRO repair, single lane" },
    { from: "Batal", to: "Kunzum La", status: "open", note: "Opened May 18" },
    { from: "Kunzum", to: "Kaza", status: "open", note: "Gravel descent" },
    { from: "Sumdo", to: "Reckong Peo", status: "partial", note: "Rockfall zone" },
  ],
  checklist: [
    { category: "Clothing", items: [
      { name: "Thermal innerwear ×2", essential: true, affiliateLink: "https://www.amazon.in/s?k=Thermal+innerwear&tag=travelboa-21", affiliateStore: "Amazon", price: "₹799" },
      { name: "Down jacket / heavy fleece", essential: true, affiliateLink: "https://www.decathlon.in/search?Ntt=Down+jacket+++heavy+fleece", affiliateStore: "Decathlon", price: "₹3,999" },
      { name: "Windproof shell jacket", essential: true, affiliateLink: "https://www.amazon.in/s?k=Windproof+shell+jacket&tag=travelboa-21", affiliateStore: "Amazon", price: "₹2,499" },
      { name: "Trek pants ×2", essential: true },
      { name: "Warm socks ×4", essential: true },
      { name: "Beanie + Balaclava", essential: true },
      { name: "Riding gloves (if biking)", essential: false },
      { name: "Rain poncho / jacket", essential: true },
      { name: "Sunglasses UV400 (polarized)", essential: true },
    ]},
    { category: "Gear", items: [
      { name: "Riding/trekking shoes", essential: true, affiliateLink: "https://www.decathlon.in/search?Ntt=Riding+trekking+shoes", affiliateStore: "Decathlon", price: "₹3,999" },
      { name: "Backpack 40–60L", essential: true, affiliateLink: "https://www.amazon.in/s?k=Backpack+40-60L&tag=travelboa-21", affiliateStore: "Amazon", price: "₹2,499" },
      { name: "Sleeping bag -5°C (if camping)", essential: false, affiliateLink: "https://www.amazon.in/s?k=Sleeping+bag+-5°C+(if+camping)&tag=travelboa-21", affiliateStore: "Amazon", price: "₹3,499" },
      { name: "Headlamp", essential: true, affiliateLink: "https://www.amazon.in/s?k=Headlamp&tag=travelboa-21", affiliateStore: "Amazon", price: "₹499" },
      { name: "Power bank ×2 (20K each)", essential: true, affiliateLink: "https://www.amazon.in/s?k=Power+bank+×2+(20K+each)&tag=travelboa-21", affiliateStore: "Amazon", price: "₹1,499" },
      { name: "Water bottle 1L", essential: true },
      { name: "Bungee cords (bike luggage)", essential: false },
    ]},
    { category: "Health", items: [
      { name: "Diamox (altitude)", essential: true },
      { name: "Personal medicines (10 days)", essential: true },
      { name: "ORS packets ×10", essential: true },
      { name: "Sunscreen SPF 50+", essential: true, affiliateLink: "https://www.amazon.in/s?k=Sunscreen+SPF+50+&tag=travelboa-21", affiliateStore: "Amazon", price: "₹399" },
      { name: "Lip balm SPF", essential: false },
      { name: "First aid kit", essential: true },
      { name: "Dettol / antiseptic", essential: true },
    ]},
    { category: "Documents", items: [
      { name: "Aadhaar / Passport", essential: true },
      { name: "ILP (get at Kaza SDM)", essential: true },
      { name: "Rohtang permit (printed)", essential: true },
      { name: "Vehicle docs + DL + RC + insurance", essential: true },
      { name: "Cash ₹15,000+", essential: true },
    ]},
  ],
  faq: [
    { q: "Is Spiti safe for solo travellers?", a: "Yes. Spiti is one of the safest regions in India. Locals are friendly and helpful. Solo bikers and backpackers are common. The main risk is road conditions and altitude, not safety." },
    { q: "Can I do Spiti in a car?", a: "Yes, with a high-clearance vehicle (Innova, Bolero, Thar). Sedan not recommended — water crossings and rough patches will scrape the bottom. Most people hire an Innova from Manali." },
    { q: "When does Kunzum La open?", a: "Usually mid-May to early June, depending on snow clearance by BRO. Closes by mid-October. Check BRO updates before planning." },
    { q: "Is there internet in Spiti?", a: "BSNL postpaid works intermittently in Kaza. Jio is patchy. No signal between Batal and Losar. Expect to be offline for large stretches." },
    { q: "How much fuel should I carry?", a: "Fill full tank at Manali (or Reckong Peo). Carry a 5–10L jerry can. The Kaza pump is unreliable. Plan for 200+ km without refuelling." },
  ],
  emergency: [
    { name: "Kaza PHC", number: "01906-222340" },
    { name: "SDM Kaza", number: "01906-222224" },
    { name: "BRO Helpline", number: "1800-180-6763" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [
    { slug: "manali-kaza-route", title: "Manali to Kaza route guide", description: "Km-by-km via Rohtang and Kunzum" },
    { slug: "kaza-shimla-route", title: "Kaza to Shimla via Kinnaur", description: "The HT Highway route" },
    { slug: "chandratal", title: "Chandratal Lake guide", description: "How to reach, camping, permits" },
    { slug: "packing", title: "Packing checklist", description: "Cold desert specific gear list" },
    { slug: "permits", title: "Permits guide", description: "ILP, Rohtang, camping permits" },
    { slug: "essentials", title: "Fuel, ATM & network", description: "The most important page for Spiti" },
    { slug: "accommodation", title: "Where to stay", description: "Homestays, guesthouses, camps" },
    { slug: "best-time", title: "Best time to visit", description: "Month-by-month breakdown" },
  ],
  metaTitle: "Spiti Valley Road Trip 2026: Route, Permits, Budget from Dehradun | TravelBoa",
  metaDescription: "Plan your Spiti Valley road trip with this first-hand guide. Manali-Kaza route, ILP permits, fuel stops, ATM locations, camping at Chandratal, and budget breakdown.",
};
