import type { DestinationData } from "./types";

export const valleyOfFlowers: DestinationData = {
  slug: "valley-of-flowers",
  name: "Valley of Flowers",
  tagline: "UNESCO World Heritage trek - 500+ wildflower species at 3,658m",
  region: "Garhwal",
  state: "Uttarakhand",
  type: "adventure",
  altitude: 3658,
  temp: 10,
  weather: "Monsoon bloom",
  season: "July-September (peak bloom August)",
  duration: "4-5 days",
  budget: { min: 5000, max: 15000 },
  heroGradient: "linear-gradient(150deg,#4a1060,#86198f 60%,#c026d3)",
  metaTitle: "Valley of Flowers Trek Guide 2026 - Govindghat Route, Permits, August Bloom | TravelBoa",
  metaDescription: "Valley of Flowers trek guide from Govindghat. 17 km trek logistics, August peak bloom timing, Hemkund Sahib combo, permits, Ghangaria base camp, flower identification, and Badrinath combination itinerary.",
  quickStats: [
    { label: "Valley altitude", value: "3,658m", icon: "🌸" },
    { label: "Trek distance", value: "17 km from Govindghat", icon: "🥾" },
    { label: "Best month", value: "August", icon: "📅" },
    { label: "Entry fee", value: "Rs 150 + Rs 600", icon: "🎫" },
    { label: "Duration", value: "4-5 days", icon: "⏱️" },
    { label: "Species", value: "500+", icon: "🌺" },
  ],
  intro: "Every other destination on this site recommends avoiding July-August. Valley of Flowers is the exception. The bloom peaks in August. The valley floor - 87 square kilometres of alpine meadow at 3,658m in the Zanskar range - is only what it is when the monsoon fills it with 500+ species of wildflowers, some of which exist nowhere else on the Indian subcontinent.\n\nI went in the first week of August. The trail from Ghangaria to the valley entrance was slippery from three days of rain. The valley itself was full cloud-cover for my first morning. The second morning was clear from 7-10 AM before clouds moved in again. Those three hours were worth the entire journey.",
  sections: [
    { id: "route", title: "The route: Govindghat to Valley of Flowers", icon: "🥾",
      content: "Govindghat (1,828m) is the trailhead, 25 km before Badrinath on the Joshimath-Badrinath road. From Rishikesh: 270 km, 9-10 hours by road.\n\nGovindghat to Ghangaria: 14 km trek, 1,280m elevation gain. Takes 5-7 hours. Well-marked trail along the Pushpawati river. Mule service available (Rs 800-1,200 one way) for those who do not want to trek. Helicopter service from Govindghat to Ghangaria operates seasonally (Rs 3,000-4,000 one way).\n\nGhangaria (3,049m) is the base camp. All accommodation and food is here. No camping allowed in the valley itself.\n\nGhangaria to Valley of Flowers entrance: 3 km, moderate trail. Entry gate opens at 7 AM. Last entry at 2 PM. Must exit by 5 PM. No overnight stays in the valley.\n\nThe valley floor is a 5 km walk from the entrance. Total round trip from Ghangaria to the valley floor and back: 16 km, 6-8 hours." },
    { id: "hemkund", title: "Hemkund Sahib: the worthwhile detour", icon: "🛕",
      content: "Hemkund Sahib is a Sikh pilgrimage site at 4,632m - one of the highest gurudwaras in the world. The trek from Ghangaria is 6 km one way with 1,583m elevation gain. Takes 4-5 hours up, 2-3 hours down.\n\nThe glacial lake at Hemkund is surrounded by seven peaks. The gurudwara offers free langar (community meal) and basic accommodation. Even non-Sikhs find the setting remarkable.\n\nRecommended itinerary: Day 1 trek to Ghangaria. Day 2 Valley of Flowers. Day 3 Hemkund Sahib. Day 4 return to Govindghat. This gives you both experiences from the same base camp." },
    { id: "august", title: "August: the counter-intuitive best month", icon: "🌧️",
      content: "In May, the valley has snow. In June, the snow melts and first flowers emerge. In July, the bloom accelerates. In August, the meadow is at full density - poppies, geraniums, primulas, brahmakamal, arisaemas, cranesbills covering the valley floor at knee-height. In September, it begins to thin. By October, snow returns.\n\nThe trade-off is monsoon. August means rain. The trail will be wet and slippery. Leeches are present on the lower sections. Cloud cover can obscure the valley until mid-morning. You will get wet.\n\nBut the flowers are why you are going. The flowers are in August. If you want clear weather, go to Kedarnath in October. If you want flowers, accept August rain and pack accordingly.\n\nBring waterproof shoes, rain gear, leech socks, and a sense of humor about getting damp. The mornings between 7-10 AM are often clear enough for photography before clouds build." },
    { id: "permits", title: "Permits and entry fees", icon: "🎫",
      content: "Valley of Flowers entry fee: Rs 150 per person per day (Indian citizens). Rs 600 for foreigners. Payable at the forest department counter at Ghangaria.\n\nBiosphere Reserve fee: Rs 600 per person. This is a separate fee, also payable at Ghangaria.\n\nTotal entry cost: Rs 750 per day for Indian citizens, Rs 1,200 for foreigners.\n\nNo advance booking required. Pay at the counter on the day of visit. The fees support conservation of the UNESCO World Heritage site.\n\nCamera fee: Rs 500 for professional cameras. Phone cameras are free." },
    { id: "ghangaria", title: "Ghangaria base camp logistics", icon: "🏕️",
      content: "Ghangaria is a small settlement at 3,049m that exists almost entirely to serve Valley of Flowers and Hemkund Sahib visitors. Open June to October.\n\nAccommodation: GMVN guesthouse Rs 800-2,000. Private guesthouses Rs 500-1,500. Gurudwara Gobind Dham offers free accommodation and langar for all visitors regardless of religion.\n\nFood: Multiple dhabas serving dal, rice, Maggi, parathas. Prices are higher than valley towns (Rs 150-300 per meal) because everything arrives by mule.\n\nFacilities: No ATM. No reliable mobile signal (BSNL occasionally works). One small medical post. Carry all cash you need from Joshimath.\n\nPower: Most guesthouses have solar power and can charge phones. Bring a power bank as backup." },
    { id: "flowers", title: "Flower highlights by month", icon: "🌺",
      content: "June: Early bloomers - primulas, marsh marigolds, wild roses. Snow still present in upper sections. Valley partially accessible.\n\nJuly: Geraniums, potentillas, and the first Himalayan poppies. Ground cover building. Good for photography in the gaps between rain.\n\nAugust (peak): Full bloom. Brahmakamal (the sacred lotus of the Himalayas), blue poppies, arisaemas, cobra lilies, wild orchids, balsams. The valley floor is a continuous carpet of color. Maximum species diversity.\n\nSeptember: Thinning bloom. Late-season species include gentians and asters. Cooler temperatures. Fewer visitors. Still worthwhile but past peak." },
    { id: "budget", title: "Budget breakdown", icon: "💰",
      content: "Transport Rishikesh to Govindghat: Bus Rs 500-700, shared taxi Rs 800-1,200.\n\nGovindghat to Ghangaria: Trek (free) or mule Rs 800-1,200 or helicopter Rs 3,000-4,000.\n\nAccommodation Ghangaria (2-3 nights): Rs 500-1,500/night. Gurudwara: free.\n\nFood (4-5 days): Rs 200-350/day at dhabas.\n\nEntry fees: Rs 750/day (1-2 days = Rs 750-1,500).\n\nReturn transport: Same as arrival.\n\nTotal budget estimate: Rs 5,000-8,000 (budget with trek and gurudwara stay) to Rs 12,000-15,000 (mule both ways, private guesthouse)." },
    { id: "packing", title: "What to pack", icon: "🎒",
      content: "Waterproof trekking shoes - mandatory. The trail is wet throughout August. See /gear/trekking-shoes-under-5000 for options.\n\nRain gear: waterproof jacket or poncho. You will get wet. See /gear/rain-ponchos-char-dham.\n\nLeech socks or salt: leeches are present on the lower trail sections in monsoon. Leech socks (Rs 200-400 on Amazon) or carrying salt works.\n\nCamera with rain protection: the flowers are the entire point. Protect your camera.\n\nWarm layers: Ghangaria at 3,049m is cold in the morning. Fleece and thermals for camp.\n\nFirst aid kit with Diamox. The valley is at 3,658m and Hemkund at 4,632m. See /guides/acclimatize-above-3000m.\n\nCash: Rs 5,000-8,000 from Joshimath. No ATM at Ghangaria." },
    { id: "combo", title: "Combining with Badrinath and Char Dham", icon: "🗺️",
      content: "Govindghat is 25 km before Badrinath on the same road. The combination itinerary:\n\nDay 1: Joshimath to Govindghat, trek to Ghangaria (14 km).\nDay 2: Valley of Flowers (full day).\nDay 3: Hemkund Sahib (optional) or second Valley day.\nDay 4: Return to Govindghat, drive to Badrinath (25 km).\nDay 5: Badrinath darshan + Mana village.\nDay 6: Return to Joshimath or continue to Kedarnath via Rudraprayag.\n\nThis works best in August-September when the valley is in bloom and Badrinath has lower crowds. See /badrinath for the full Badrinath guide." },
  ],
  weatherPoints: [
    { location: "Govindghat", altitude: 1828, temp: 20, weather: "Warm rain" },
    { location: "Ghangaria", altitude: 3049, temp: 12, weather: "Cool rain" },
    { location: "Valley floor", altitude: 3658, temp: 8, weather: "Cloud and rain" },
    { location: "Hemkund Sahib", altitude: 4632, temp: 3, weather: "Cold" },
  ],
  routes: [
    { from: "Rishikesh", to: "Govindghat", status: "open", note: "270 km, 9-10 hrs" },
    { from: "Joshimath", to: "Govindghat", status: "open", note: "20 km" },
    { from: "Govindghat", to: "Ghangaria", status: "open", note: "14 km trek" },
    { from: "Ghangaria", to: "Valley of Flowers", status: "open", note: "3 km trail" },
    { from: "Ghangaria", to: "Hemkund Sahib", status: "open", note: "6 km trek" },
  ],
  checklist: [
    { category: "Essential gear", items: [
      { name: "Waterproof trekking shoes", essential: true },
      { name: "Rain jacket or poncho", essential: true },
      { name: "Leech socks or salt", essential: true },
      { name: "Warm fleece for camp", essential: true },
      { name: "Thermal base layer", essential: true },
    ] },
    { category: "Trail items", items: [
      { name: "Water bottle 1.5L", essential: true },
      { name: "Camera with rain cover", essential: false },
      { name: "Headlamp", essential: true },
      { name: "Sunscreen SPF50", essential: true },
      { name: "Power bank", essential: true },
      { name: "Cash Rs 5,000-8,000", essential: true },
    ] },
    { category: "Health", items: [
      { name: "Diamox 250mg", essential: true },
      { name: "First aid kit", essential: true },
      { name: "ORS sachets x5", essential: true },
      { name: "Anti-leech spray", essential: false },
    ] },
  ],
  faq: [
    { q: "When is the best time to visit Valley of Flowers?", a: "First two weeks of August for peak bloom. Late July is also good. September has fewer flowers but clearer weather. The valley is closed October to June." },
    { q: "Can I camp in the Valley of Flowers?", a: "No. Camping inside the valley is strictly prohibited. All visitors must stay in Ghangaria and do the valley as a day trip. Entry 7 AM, exit by 5 PM." },
    { q: "Are leeches a serious problem?", a: "Leeches are present on the lower trail sections in monsoon. They are not dangerous but uncomfortable. Leech socks, salt, or tobacco paste at your socks and shoe cuffs works. Check your legs at rest stops." },
    { q: "Is the mule ride to Ghangaria worth it?", a: "If you have knee issues or limited fitness, yes. The 14 km with 1,280m gain is a genuine trek. Mule cost Rs 800-1,200. The mule cannot enter the valley itself - you walk the valley portion." },
    { q: "Can I combine Valley of Flowers with Badrinath?", a: "Yes, highly recommended. Govindghat (trailhead) is 25 km before Badrinath on the same road. Do the valley first, then continue to Badrinath for darshan." },
    { q: "What is Brahmakamal and when does it bloom?", a: "Brahmakamal (Saussurea obvallata) is a sacred flower that blooms in August at altitudes above 3,500m. It is the state flower of Uttarakhand. The valley is one of the most reliable places to see it in bloom." },
  ],
  emergency: [
    { name: "Ghangaria Medical Post", number: "No direct line" },
    { name: "Joshimath Hospital", number: "01389-222215" },
    { name: "SDRF Uttarakhand", number: "1070" },
    { name: "Disaster Helpline", number: "112" },
  ],
  subPages: [
    { slug: "packing", title: "Valley of Flowers packing checklist", description: "What to pack for the monsoon trek to Valley of Flowers" },
  ],
};
